# Generated by Django 5.1 on 2024-09-30 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploreFairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firsrtName', models.CharField(max_length=50)),
                ('secondName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FairRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registrationDate', models.DateField()),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairManagement.aspirant')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploreFairs.jobfair')),
            ],
        ),
    ]
