# Generated by Django 5.1 on 2024-09-30 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fairAttendance', '0001_initial'),
        ('fairManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='registration_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairManagement.fairregistration'),
        ),
    ]
