jQuery(document).ready(function ($) {
  // Array Municipios Listado

  var antioquía = [
    { display: "Medellín", value: "Medellín" },
    { display: "Abejorral", value: "Abejorral" },
    { display: "Abriaquí", value: "Abriaquí" },
    { display: "Alejandría", value: "Alejandría" },
    { display: "Amagá", value: "Amagá" },
    { display: "Amalfi", value: "Amalfi" },
    { display: "Andes", value: "Andes" },
    { display: "Angelópolis", value: "Angelópolis" },
    { display: "Angostura", value: "Angostura" },
    { display: "Anorí", value: "Anorí" },
    { display: "Santa fé de antioquia", value: "Santa fé de antioquia" },
    { display: "Anzá", value: "Anzá" },
    { display: "Apartadó", value: "Apartadó" },
    { display: "Arboletes", value: "Arboletes" },
    { display: "Argelia", value: "Argelia" },
    { display: "Armenia", value: "Armenia" },
    { display: "Barbosa", value: "Barbosa" },
    { display: "Belmira", value: "Belmira" },
    { display: "Bello", value: "Bello" },
    { display: "Betania", value: "Betania" },
    { display: "Betulia", value: "Betulia" },
    { display: "Ciudad bolívar", value: "Ciudad bolívar" },
    { display: "Briceño", value: "Briceño" },
    { display: "Buriticá", value: "Buriticá" },
    { display: "Cáceres", value: "Cáceres" },
    { display: "Caicedo", value: "Caicedo" },
    { display: "Caldas", value: "Caldas" },
    { display: "Campamento", value: "Campamento" },
    { display: "Cañasgordas", value: "Cañasgordas" },
    { display: "Caracolí", value: "Caracolí" },
    { display: "Caramanta", value: "Caramanta" },
    { display: "Carepa", value: "Carepa" },
    { display: "El carmen de viboral", value: "El carmen de viboral" },
    { display: "Carolina", value: "Carolina" },
    { display: "Caucasia", value: "Caucasia" },
    { display: "Chigorodó", value: "Chigorodó" },
    { display: "Cisneros", value: "Cisneros" },
    { display: "Cocorná", value: "Cocorná" },
    { display: "Concepción", value: "Concepción" },
    { display: "Concordia", value: "Concordia" },
    { display: "Copacabana", value: "Copacabana" },
    { display: "Dabeiba", value: "Dabeiba" },
    { display: "Donmatías", value: "Donmatías" },
    { display: "Ebéjico", value: "Ebéjico" },
    { display: "El bagre", value: "El bagre" },
    { display: "Entrerríos", value: "Entrerríos" },
    { display: "Envigado", value: "Envigado" },
    { display: "Fredonia", value: "Fredonia" },
    { display: "Frontino", value: "Frontino" },
    { display: "Giraldo", value: "Giraldo" },
    { display: "Girardota", value: "Girardota" },
    { display: "Gómez plata", value: "Gómez plata" },
    { display: "Granada", value: "Granada" },
    { display: "Guadalupe", value: "Guadalupe" },
    { display: "Guarne", value: "Guarne" },
    { display: "Guatapé", value: "Guatapé" },
    { display: "Heliconia", value: "Heliconia" },
    { display: "Hispania", value: "Hispania" },
    { display: "Itagüí", value: "Itagüí" },
    { display: "Ituango", value: "Ituango" },
    { display: "Jardín", value: "Jardín" },
    { display: "Jericó", value: "Jericó" },
    { display: "La ceja", value: "La ceja" },
    { display: "La estrella", value: "La estrella" },
    { display: "La pintada", value: "La pintada" },
    { display: "La unión", value: "La unión" },
    { display: "Liborina", value: "Liborina" },
    { display: "Maceo", value: "Maceo" },
    { display: "Marinilla", value: "Marinilla" },
    { display: "Montebello", value: "Montebello" },
    { display: "Murindó", value: "Murindó" },
    { display: "Mutatá", value: "Mutatá" },
    { display: "Nariño", value: "Nariño" },
    { display: "Necoclí", value: "Necoclí" },
    { display: "Nechí", value: "Nechí" },
    { display: "Olaya", value: "Olaya" },
    { display: "Peñol", value: "Peñol" },
    { display: "Peque", value: "Peque" },
    { display: "Pueblorrico", value: "Pueblorrico" },
    { display: "Puerto berrío", value: "Puerto berrío" },
    { display: "Puerto nare", value: "Puerto nare" },
    { display: "Puerto triunfo", value: "Puerto triunfo" },
    { display: "Remedios", value: "Remedios" },
    { display: "Retiro", value: "Retiro" },
    { display: "Rionegro", value: "Rionegro" },
    { display: "Sabanalarga", value: "Sabanalarga" },
    { display: "Sabaneta", value: "Sabaneta" },
    { display: "Salgar", value: "Salgar" },
    { display: "San andrés de cuerquía", value: "San andrés de cuerquía" },
    { display: "San carlos", value: "San carlos" },
    { display: "San francisco", value: "San francisco" },
    { display: "San jerónimo", value: "San jerónimo" },
    { display: "San josé de la montaña", value: "San josé de la montaña" },
    { display: "San juan de urabá", value: "San juan de urabá" },
    { display: "San luis", value: "San luis" },
    { display: "San pedro de los milagros", value: "San pedro de los milagros" },
    { display: "San pedro de urabá", value: "San pedro de urabá" },
    { display: "San rafael", value: "San rafael" },
    { display: "San roque", value: "San roque" },
    { display: "San vicente ferrer", value: "San vicente ferrer" },
    { display: "Santa bárbara", value: "Santa bárbara" },
    { display: "Santa rosa de osos", value: "Santa rosa de osos" },
    { display: "Santo domingo", value: "Santo domingo" },
    { display: "El santuario", value: "El santuario" },
    { display: "Segovia", value: "Segovia" },
    { display: "Sonsón", value: "Sonsón" },
    { display: "Sopetrán", value: "Sopetrán" },
    { display: "Támesis", value: "Támesis" },
    { display: "Tarazá", value: "Tarazá" },
    { display: "Tarso", value: "Tarso" },
    { display: "Titiribí", value: "Titiribí" },
    { display: "Toledo", value: "Toledo" },
    { display: "Turbo", value: "Turbo" },
    { display: "Uramita", value: "Uramita" },
    { display: "Urrao", value: "Urrao" },
    { display: "Valdivia", value: "Valdivia" },
    { display: "Valparaíso", value: "Valparaíso" },
    { display: "Vegachí", value: "Vegachí" },
    { display: "Venecia", value: "Venecia" },
    { display: "Vigía del fuerte", value: "Vigía del fuerte" },
    { display: "Yalí", value: "Yalí" },
    { display: "Yarumal", value: "Yarumal" },
    { display: "Yolombó", value: "Yolombó" },
    { display: "Yondó", value: "Yondó" },
    { display: "Zaragoza", value: "Zaragoza" }];

  var atlántico = [
    { display: "Barranquilla", value: "Barranquilla" },
    { display: "Baranoa", value: "Baranoa" },
    { display: "Campo de la cruz", value: "Campo de la cruz" },
    { display: "Candelaria", value: "Candelaria" },
    { display: "Galapa", value: "Galapa" },
    { display: "Juan de acosta", value: "Juan de acosta" },
    { display: "Luruaco", value: "Luruaco" },
    { display: "Malambo", value: "Malambo" },
    { display: "Manatí", value: "Manatí" },
    { display: "Palmar de varela", value: "Palmar de varela" },
    { display: "Piojó", value: "Piojó" },
    { display: "Polonuevo", value: "Polonuevo" },
    { display: "Ponedera", value: "Ponedera" },
    { display: "Puerto colombia", value: "Puerto colombia" },
    { display: "Repelón", value: "Repelón" },
    { display: "Sabanagrande", value: "Sabanagrande" },
    { display: "Sabanalarga", value: "Sabanalarga" },
    { display: "Santa lucía", value: "Santa lucía" },
    { display: "Santo tomás", value: "Santo tomás" },
    { display: "Soledad", value: "Soledad" },
    { display: "Suan", value: "Suan" },
    { display: "Tubará", value: "Tubará" },
    { display: "Usiacurí", value: "Usiacurí" }];

  var bolívar = [
    { display: "Cartagena de indias", value: "Cartagena de indias" },
    { display: "Achí", value: "Achí" },
    { display: "Altos del rosario", value: "Altos del rosario" },
    { display: "Arenal", value: "Arenal" },
    { display: "Arjona", value: "Arjona" },
    { display: "Arroyohondo", value: "Arroyohondo" },
    { display: "Barranco de loba", value: "Barranco de loba" },
    { display: "Calamar", value: "Calamar" },
    { display: "Cantagallo", value: "Cantagallo" },
    { display: "Cicuco", value: "Cicuco" },
    { display: "Córdoba", value: "Córdoba" },
    { display: "Clemencia", value: "Clemencia" },
    { display: "El carmen de bolívar", value: "El carmen de bolívar" },
    { display: "El guamo", value: "El guamo" },
    { display: "El peñón", value: "El peñón" },
    { display: "Hatillo de loba", value: "Hatillo de loba" },
    { display: "Magangué", value: "Magangué" },
    { display: "Mahates", value: "Mahates" },
    { display: "Margarita", value: "Margarita" },
    { display: "María la baja", value: "María la baja" },
    { display: "Montecristo", value: "Montecristo" },
    { display: "Mompós", value: "Mompós" },
    { display: "Morales", value: "Morales" },
    { display: "Norosí", value: "Norosí" },
    { display: "Pinillos", value: "Pinillos" },
    { display: "Regidor", value: "Regidor" },
    { display: "Río viejo", value: "Río viejo" },
    { display: "San cristóbal", value: "San cristóbal" },
    { display: "San estanislao", value: "San estanislao" },
    { display: "San fernando", value: "San fernando" },
    { display: "San jacinto", value: "San jacinto" },
    { display: "San jacinto del cauca", value: "San jacinto del cauca" },
    { display: "San juan nepomuceno", value: "San juan nepomuceno" },
    { display: "San martín de loba", value: "San martín de loba" },
    { display: "San pablo", value: "San pablo" },
    { display: "Santa catalina", value: "Santa catalina" },
    { display: "Santa rosa", value: "Santa rosa" },
    { display: "Santa rosa del sur", value: "Santa rosa del sur" },
    { display: "Simití", value: "Simití" },
    { display: "Soplaviento", value: "Soplaviento" },
    { display: "Talaigua nuevo", value: "Talaigua nuevo" },
    { display: "Tiquisio", value: "Tiquisio" },
    { display: "Turbaco", value: "Turbaco" },
    { display: "Turbaná", value: "Turbaná" },
    { display: "Villanueva", value: "Villanueva" },
    { display: "Zambrano", value: "Zambrano" }];


  var boyacá = [
    { display: "Tunja", value: "Tunja" },
    { display: "Almeida", value: "Almeida" },
    { display: "Aquitania", value: "Aquitania" },
    { display: "Arcabuco", value: "Arcabuco" },
    { display: "Belén", value: "Belén" },
    { display: "Berbeo", value: "Berbeo" },
    { display: "Betéitiva", value: "Betéitiva" },
    { display: "Boavita", value: "Boavita" },
    { display: "Boyacá", value: "Boyacá" },
    { display: "Briceño", value: "Briceño" },
    { display: "Buenavista", value: "Buenavista" },
    { display: "Busbanzá", value: "Busbanzá" },
    { display: "Caldas", value: "Caldas" },
    { display: "Campohermoso", value: "Campohermoso" },
    { display: "Cerinza", value: "Cerinza" },
    { display: "Chinavita", value: "Chinavita" },
    { display: "Chiquinquirá", value: "Chiquinquirá" },
    { display: "Chiscas", value: "Chiscas" },
    { display: "Chita", value: "Chita" },
    { display: "Chitaraque", value: "Chitaraque" },
    { display: "Chivatá", value: "Chivatá" },
    { display: "Ciénega", value: "Ciénega" },
    { display: "Cómbita", value: "Cómbita" },
    { display: "Coper", value: "Coper" },
    { display: "Corrales", value: "Corrales" },
    { display: "Covarachía", value: "Covarachía" },
    { display: "Cubará", value: "Cubará" },
    { display: "Cucaita", value: "Cucaita" },
    { display: "Cuítiva", value: "Cuítiva" },
    { display: "Chíquiza", value: "Chíquiza" },
    { display: "Chivor", value: "Chivor" },
    { display: "Duitama", value: "Duitama" },
    { display: "El cocuy", value: "El cocuy" },
    { display: "El espino", value: "El espino" },
    { display: "Firavitoba", value: "Firavitoba" },
    { display: "Floresta", value: "Floresta" },
    { display: "Gachantivá", value: "Gachantivá" },
    { display: "Gámeza", value: "Gámeza" },
    { display: "Garagoa", value: "Garagoa" },
    { display: "Guacamayas", value: "Guacamayas" },
    { display: "Guateque", value: "Guateque" },
    { display: "Guayatá", value: "Guayatá" },
    { display: "Güicán", value: "Güicán" },
    { display: "Iza", value: "Iza" },
    { display: "Jenesano", value: "Jenesano" },
    { display: "Jericó", value: "Jericó" },
    { display: "Labranzagrande", value: "Labranzagrande" },
    { display: "La capilla", value: "La capilla" },
    { display: "La victoria", value: "La victoria" },
    { display: "La uvita", value: "La uvita" },
    { display: "Villa de leyva", value: "Villa de leyva" },
    { display: "Macanal", value: "Macanal" },
    { display: "Maripí", value: "Maripí" },
    { display: "Miraflores", value: "Miraflores" },
    { display: "Mongua", value: "Mongua" },
    { display: "Monguí", value: "Monguí" },
    { display: "Moniquirá", value: "Moniquirá" },
    { display: "Motavita", value: "Motavita" },
    { display: "Muzo", value: "Muzo" },
    { display: "Nobsa", value: "Nobsa" },
    { display: "Nuevo colón", value: "Nuevo colón" },
    { display: "Oicatá", value: "Oicatá" },
    { display: "Otanche", value: "Otanche" },
    { display: "Pachavita", value: "Pachavita" },
    { display: "Páez", value: "Páez" },
    { display: "Paipa", value: "Paipa" },
    { display: "Pajarito", value: "Pajarito" },
    { display: "Panqueba", value: "Panqueba" },
    { display: "Pauna", value: "Pauna" },
    { display: "Paya", value: "Paya" },
    { display: "Paz de río", value: "Paz de río" },
    { display: "Pesca", value: "Pesca" },
    { display: "Pisba", value: "Pisba" },
    { display: "Puerto boyacá", value: "Puerto boyacá" },
    { display: "Quípama", value: "Quípama" },
    { display: "Ramiriquí", value: "Ramiriquí" },
    { display: "Ráquira", value: "Ráquira" },
    { display: "Rondón", value: "Rondón" },
    { display: "Saboyá", value: "Saboyá" },
    { display: "Sáchica", value: "Sáchica" },
    { display: "Samacá", value: "Samacá" },
    { display: "San eduardo", value: "San eduardo" },
    { display: "San josé de pare", value: "San josé de pare" },
    { display: "San luis de gaceno", value: "San luis de gaceno" },
    { display: "San mateo", value: "San mateo" },
    { display: "San miguel de sema", value: "San miguel de sema" },
    { display: "San pablo de borbur", value: "San pablo de borbur" },
    { display: "Santana", value: "Santana" },
    { display: "Santa maría", value: "Santa maría" },
    { display: "Santa rosa de viterbo", value: "Santa rosa de viterbo" },
    { display: "Santa sofía", value: "Santa sofía" },
    { display: "Sativanorte", value: "Sativanorte" },
    { display: "Sativasur", value: "Sativasur" },
    { display: "Siachoque", value: "Siachoque" },
    { display: "Soatá", value: "Soatá" },
    { display: "Socotá", value: "Socotá" },
    { display: "Socha", value: "Socha" },
    { display: "Sogamoso", value: "Sogamoso" },
    { display: "Somondoco", value: "Somondoco" },
    { display: "Sora", value: "Sora" },
    { display: "Sotaquirá", value: "Sotaquirá" },
    { display: "Soracá", value: "Soracá" },
    { display: "Susacón", value: "Susacón" },
    { display: "Sutamarchán", value: "Sutamarchán" },
    { display: "Sutatenza", value: "Sutatenza" },
    { display: "Tasco", value: "Tasco" },
    { display: "Tenza", value: "Tenza" },
    { display: "Tibaná", value: "Tibaná" },
    { display: "Tibasosa", value: "Tibasosa" },
    { display: "Tinjacá", value: "Tinjacá" },
    { display: "Tipacoque", value: "Tipacoque" },
    { display: "Toca", value: "Toca" },
    { display: "Togüí", value: "Togüí" },
    { display: "Tópaga", value: "Tópaga" },
    { display: "Tota", value: "Tota" },
    { display: "Tununguá", value: "Tununguá" },
    { display: "Turmequé", value: "Turmequé" },
    { display: "Tuta", value: "Tuta" },
    { display: "Tutazá", value: "Tutazá" },
    { display: "Úmbita", value: "Úmbita" },
    { display: "Ventaquemada", value: "Ventaquemada" },
    { display: "Viracachá", value: "Viracachá" },
    { display: "Zetaquira", value: "Zetaquira" }];


  var caldas = [
    { display: "Manizales", value: "Manizales" },
    { display: "Aguadas", value: "Aguadas" },
    { display: "Anserma", value: "Anserma" },
    { display: "Aranzazu", value: "Aranzazu" },
    { display: "Belalcázar", value: "Belalcázar" },
    { display: "Chinchiná", value: "Chinchiná" },
    { display: "Filadelfia", value: "Filadelfia" },
    { display: "La dorada", value: "La dorada" },
    { display: "La merced", value: "La merced" },
    { display: "Manzanares", value: "Manzanares" },
    { display: "Marmato", value: "Marmato" },
    { display: "Marquetalia", value: "Marquetalia" },
    { display: "Marulanda", value: "Marulanda" },
    { display: "Neira", value: "Neira" },
    { display: "Norcasia", value: "Norcasia" },
    { display: "Pácora", value: "Pácora" },
    { display: "Palestina", value: "Palestina" },
    { display: "Pensilvania", value: "Pensilvania" },
    { display: "Riosucio", value: "Riosucio" },
    { display: "Risaralda", value: "Risaralda" },
    { display: "Salamina", value: "Salamina" },
    { display: "Samaná", value: "Samaná" },
    { display: "San josé", value: "San josé" },
    { display: "Supía", value: "Supía" },
    { display: "Victoria", value: "Victoria" },
    { display: "Villamaría", value: "Villamaría" },
    { display: "Viterbo", value: "Viterbo" }];

  var caquetá = [
    { display: "Florencia", value: "Florencia" },
    { display: "Albania", value: "Albania" },
    { display: "Belén de los andaquíes", value: "Belén de los andaquíes" },
    { display: "Cartagena del chairá", value: "Cartagena del chairá" },
    { display: "Curillo", value: "Curillo" },
    { display: "El doncello", value: "El doncello" },
    { display: "El paujíl", value: "El paujíl" },
    { display: "La montañita", value: "La montañita" },
    { display: "Milán", value: "Milán" },
    { display: "Morelia", value: "Morelia" },
    { display: "Puerto rico", value: "Puerto rico" },
    { display: "San josé del fragua", value: "San josé del fragua" },
    { display: "San vicente del caguán", value: "San vicente del caguán" },
    { display: "Solano", value: "Solano" },
    { display: "Solita", value: "Solita" },
    { display: "Valparaíso", value: "Valparaíso" }];

  var cauca = [
    { display: "Popayán", value: "Popayán" },
    { display: "Almaguer", value: "Almaguer" },
    { display: "Argelia", value: "Argelia" },
    { display: "Balboa", value: "Balboa" },
    { display: "Bolívar", value: "Bolívar" },
    { display: "Buenos aires", value: "Buenos aires" },
    { display: "Cajibío", value: "Cajibío" },
    { display: "Caldono", value: "Caldono" },
    { display: "Caloto", value: "Caloto" },
    { display: "Corinto", value: "Corinto" },
    { display: "El tambo", value: "El tambo" },
    { display: "Florencia", value: "Florencia" },
    { display: "Guachené", value: "Guachené" },
    { display: "Guapí", value: "Guapí" },
    { display: "Inzá", value: "Inzá" },
    { display: "Jambaló", value: "Jambaló" },
    { display: "La sierra", value: "La sierra" },
    { display: "La vega", value: "La vega" },
    { display: "López de micay", value: "López de micay" },
    { display: "Mercaderes", value: "Mercaderes" },
    { display: "Miranda", value: "Miranda" },
    { display: "Morales", value: "Morales" },
    { display: "Padilla", value: "Padilla" },
    { display: "Páez", value: "Páez" },
    { display: "Patía", value: "Patía" },
    { display: "Piamonte", value: "Piamonte" },
    { display: "Piendamó", value: "Piendamó" },
    { display: "Puerto tejada", value: "Puerto tejada" },
    { display: "Puracé", value: "Puracé" },
    { display: "Rosas", value: "Rosas" },
    { display: "San sebastián", value: "San sebastián" },
    { display: "Santander de quilichao", value: "Santander de quilichao" },
    { display: "Santa rosa", value: "Santa rosa" },
    { display: "Silvia", value: "Silvia" },
    { display: "Sotara", value: "Sotara" },
    { display: "Suárez", value: "Suárez" },
    { display: "Sucre", value: "Sucre" },
    { display: "Timbío", value: "Timbío" },
    { display: "Timbiquí", value: "Timbiquí" },
    { display: "Toribío", value: "Toribío" },
    { display: "Totoró", value: "Totoró" },
    { display: "Villa rica", value: "Villa rica" }];


  var cesar = [
    { display: "Valledupar", value: "Valledupar" },
    { display: "Aguachica", value: "Aguachica" },
    { display: "Agustín codazzi", value: "Agustín codazzi" },
    { display: "Astrea", value: "Astrea" },
    { display: "Becerril", value: "Becerril" },
    { display: "Bosconia", value: "Bosconia" },
    { display: "Chimichagua", value: "Chimichagua" },
    { display: "Chiriguaná", value: "Chiriguaná" },
    { display: "Curumaní", value: "Curumaní" },
    { display: "El copey", value: "El copey" },
    { display: "El paso", value: "El paso" },
    { display: "Gamarra", value: "Gamarra" },
    { display: "González", value: "González" },
    { display: "La gloria", value: "La gloria" },
    { display: "La jagua de ibirico", value: "La jagua de ibirico" },
    { display: "Manaure balcón del cesar", value: "Manaure balcón del cesar" },
    { display: "Pailitas", value: "Pailitas" },
    { display: "Pelaya", value: "Pelaya" },
    { display: "Pueblo bello", value: "Pueblo bello" },
    { display: "Río de oro", value: "Río de oro" },
    { display: "La paz", value: "La paz" },
    { display: "San alberto", value: "San alberto" },
    { display: "San diego", value: "San diego" },
    { display: "San martín", value: "San martín" },
    { display: "Tamalameque", value: "Tamalameque" }];

  var córdoba = [
    { display: "Montería", value: "Montería" },
    { display: "Ayapel", value: "Ayapel" },
    { display: "Buenavista", value: "Buenavista" },
    { display: "Canalete", value: "Canalete" },
    { display: "Cereté", value: "Cereté" },
    { display: "Chimá", value: "Chimá" },
    { display: "Chinú", value: "Chinú" },
    { display: "Ciénaga de oro", value: "Ciénaga de oro" },
    { display: "Cotorra", value: "Cotorra" },
    { display: "La apartada", value: "La apartada" },
    { display: "Lorica", value: "Lorica" },
    { display: "Los córdobas", value: "Los córdobas" },
    { display: "Momil", value: "Momil" },
    { display: "Montelíbano", value: "Montelíbano" },
    { display: "Moñitos", value: "Moñitos" },
    { display: "Planeta rica", value: "Planeta rica" },
    { display: "Pueblo nuevo", value: "Pueblo nuevo" },
    { display: "Puerto escondido", value: "Puerto escondido" },
    { display: "Puerto libertador", value: "Puerto libertador" },
    { display: "Purísima de la concepción", value: "Purísima de la concepción" },
    { display: "Sahagún", value: "Sahagún" },
    { display: "San andrés de sotavento", value: "San andrés de sotavento" },
    { display: "San antero", value: "San antero" },
    { display: "San bernardo del viento", value: "San bernardo del viento" },
    { display: "San carlos", value: "San carlos" },
    { display: "San josé de uré", value: "San josé de uré" },
    { display: "San pelayo", value: "San pelayo" },
    { display: "Tierralta", value: "Tierralta" },
    { display: "Tuchín", value: "Tuchín" },
    { display: "Valencia", value: "Valencia" }];

  var cundinamarca = [
    { display: "Agua de dios", value: "Agua de dios" },
    { display: "Albán", value: "Albán" },
    { display: "Anapoima", value: "Anapoima" },
    { display: "Anolaima", value: "Anolaima" },
    { display: "Arbeláez", value: "Arbeláez" },
    { display: "Beltrán", value: "Beltrán" },
    { display: "Bituima", value: "Bituima" },
    { display: "Bogotá, d.c.", value: "Bogotá, d.c." },
    { display: "Bojacá", value: "Bojacá" },
    { display: "Cabrera", value: "Cabrera" },
    { display: "Cachipay", value: "Cachipay" },
    { display: "Cajicá", value: "Cajicá" },
    { display: "Caparrapí", value: "Caparrapí" },
    { display: "Cáqueza", value: "Cáqueza" },
    { display: "Carmen de carupa", value: "Carmen de carupa" },
    { display: "Chaguaní", value: "Chaguaní" },
    { display: "Chía", value: "Chía" },
    { display: "Chipaque", value: "Chipaque" },
    { display: "Choachí", value: "Choachí" },
    { display: "Chocontá", value: "Chocontá" },
    { display: "Cogua", value: "Cogua" },
    { display: "Cota", value: "Cota" },
    { display: "Cucunubá", value: "Cucunubá" },
    { display: "El colegio", value: "El colegio" },
    { display: "El peñón", value: "El peñón" },
    { display: "El rosal", value: "El rosal" },
    { display: "Facatativá", value: "Facatativá" },
    { display: "Fómeque", value: "Fómeque" },
    { display: "Fosca", value: "Fosca" },
    { display: "Funza", value: "Funza" },
    { display: "Fúquene", value: "Fúquene" },
    { display: "Fusagasugá", value: "Fusagasugá" },
    { display: "Gachalá", value: "Gachalá" },
    { display: "Gachancipá", value: "Gachancipá" },
    { display: "Gachetá", value: "Gachetá" },
    { display: "Gama", value: "Gama" },
    { display: "Girardot", value: "Girardot" },
    { display: "Granada", value: "Granada" },
    { display: "Guachetá", value: "Guachetá" },
    { display: "Guaduas", value: "Guaduas" },
    { display: "Guasca", value: "Guasca" },
    { display: "Guataquí", value: "Guataquí" },
    { display: "Guatavita", value: "Guatavita" },
    { display: "Guayabal de síquima", value: "Guayabal de síquima" },
    { display: "Guayabetal", value: "Guayabetal" },
    { display: "Gutiérrez", value: "Gutiérrez" },
    { display: "Jerusalén", value: "Jerusalén" },
    { display: "Junín", value: "Junín" },
    { display: "La calera", value: "La calera" },
    { display: "La mesa", value: "La mesa" },
    { display: "La palma", value: "La palma" },
    { display: "La peña", value: "La peña" },
    { display: "La vega", value: "La vega" },
    { display: "Lenguazaque", value: "Lenguazaque" },
    { display: "Machetá", value: "Machetá" },
    { display: "Madrid", value: "Madrid" },
    { display: "Manta", value: "Manta" },
    { display: "Medina", value: "Medina" },
    { display: "Mosquera", value: "Mosquera" },
    { display: "Nariño", value: "Nariño" },
    { display: "Nemocón", value: "Nemocón" },
    { display: "Nilo", value: "Nilo" },
    { display: "Nimaima", value: "Nimaima" },
    { display: "Nocaima", value: "Nocaima" },
    { display: "Venecia", value: "Venecia" },
    { display: "Pacho", value: "Pacho" },
    { display: "Paime", value: "Paime" },
    { display: "Pandi", value: "Pandi" },
    { display: "Paratebueno", value: "Paratebueno" },
    { display: "Pasca", value: "Pasca" },
    { display: "Puerto salgar", value: "Puerto salgar" },
    { display: "Pulí", value: "Pulí" },
    { display: "Quebradanegra", value: "Quebradanegra" },
    { display: "Quetame", value: "Quetame" },
    { display: "Quipile", value: "Quipile" },
    { display: "Apulo", value: "Apulo" },
    { display: "Ricaurte", value: "Ricaurte" },
    { display: "San antonio del tequendama", value: "San antonio del tequendama" },
    { display: "San bernardo", value: "San bernardo" },
    { display: "San cayetano", value: "San cayetano" },
    { display: "San francisco", value: "San francisco" },
    { display: "San juan de rioseco", value: "San juan de rioseco" },
    { display: "Sasaima", value: "Sasaima" },
    { display: "Sesquilé", value: "Sesquilé" },
    { display: "Sibaté", value: "Sibaté" },
    { display: "Silvania", value: "Silvania" },
    { display: "Simijaca", value: "Simijaca" },
    { display: "Soacha", value: "Soacha" },
    { display: "Sopó", value: "Sopó" },
    { display: "Subachoque", value: "Subachoque" },
    { display: "Suesca", value: "Suesca" },
    { display: "Supatá", value: "Supatá" },
    { display: "Susa", value: "Susa" },
    { display: "Sutatausa", value: "Sutatausa" },
    { display: "Tabio", value: "Tabio" },
    { display: "Tausa", value: "Tausa" },
    { display: "Tena", value: "Tena" },
    { display: "Tenjo", value: "Tenjo" },
    { display: "Tibacuy", value: "Tibacuy" },
    { display: "Tibirita", value: "Tibirita" },
    { display: "Tocaima", value: "Tocaima" },
    { display: "Tocancipá", value: "Tocancipá" },
    { display: "Topaipí", value: "Topaipí" },
    { display: "Ubalá", value: "Ubalá" },
    { display: "Ubaque", value: "Ubaque" },
    { display: "Villa de san diego de ubaté", value: "Villa de san diego de ubaté" },
    { display: "Une", value: "Une" },
    { display: "Útica", value: "Útica" },
    { display: "Vergara", value: "Vergara" },
    { display: "Vianí", value: "Vianí" },
    { display: "Villagómez", value: "Villagómez" },
    { display: "Villapinzón", value: "Villapinzón" },
    { display: "Villeta", value: "Villeta" },
    { display: "Viotá", value: "Viotá" },
    { display: "Yacopí", value: "Yacopí" },
    { display: "Zipacón", value: "Zipacón" },
    { display: "Zipaquirá", value: "Zipaquirá" }];

  var chocó = [
    { display: "Quibdó", value: "Quibdó" },
    { display: "Acandí", value: "Acandí" },
    { display: "Alto baudó", value: "Alto baudó" },
    { display: "Atrato", value: "Atrato" },
    { display: "Bagadó", value: "Bagadó" },
    { display: "Bahía solano", value: "Bahía solano" },
    { display: "Bajo baudó", value: "Bajo baudó" },
    { display: "Bojayá", value: "Bojayá" },
    { display: "El cantón del san pablo", value: "El cantón del san pablo" },
    { display: "Carmen del darién", value: "Carmen del darién" },
    { display: "Cértegui", value: "Cértegui" },
    { display: "Condoto", value: "Condoto" },
    { display: "El carmen de atrato", value: "El carmen de atrato" },
    { display: "El litoral del san juan", value: "El litoral del san juan" },
    { display: "Istmina", value: "Istmina" },
    { display: "Juradó", value: "Juradó" },
    { display: "Lloró", value: "Lloró" },
    { display: "Medio atrato", value: "Medio atrato" },
    { display: "Medio baudó", value: "Medio baudó" },
    { display: "Medio san juan", value: "Medio san juan" },
    { display: "Nóvita", value: "Nóvita" },
    { display: "Nuquí", value: "Nuquí" },
    { display: "Río iró", value: "Río iró" },
    { display: "Río quito", value: "Río quito" },
    { display: "Riosucio", value: "Riosucio" },
    { display: "San josé del palmar", value: "San josé del palmar" },
    { display: "Sipí", value: "Sipí" },
    { display: "Tadó", value: "Tadó" },
    { display: "Unguía", value: "Unguía" },
    { display: "Unión panamericana", value: "Unión panamericana" }];

  var huila = [
    { display: "Neiva", value: "Neiva" },
    { display: "Acevedo", value: "Acevedo" },
    { display: "Agrado", value: "Agrado" },
    { display: "Aipe", value: "Aipe" },
    { display: "Algeciras", value: "Algeciras" },
    { display: "Altamira", value: "Altamira" },
    { display: "Baraya", value: "Baraya" },
    { display: "Campoalegre", value: "Campoalegre" },
    { display: "Colombia", value: "Colombia" },
    { display: "Elías", value: "Elías" },
    { display: "Garzón", value: "Garzón" },
    { display: "Gigante", value: "Gigante" },
    { display: "Guadalupe", value: "Guadalupe" },
    { display: "Hobo", value: "Hobo" },
    { display: "Íquira", value: "Íquira" },
    { display: "Isnos", value: "Isnos" },
    { display: "La argentina", value: "La argentina" },
    { display: "La plata", value: "La plata" },
    { display: "Nátaga", value: "Nátaga" },
    { display: "Oporapa", value: "Oporapa" },
    { display: "Paicol", value: "Paicol" },
    { display: "Palermo", value: "Palermo" },
    { display: "Palestina", value: "Palestina" },
    { display: "Pital", value: "Pital" },
    { display: "Pitalito", value: "Pitalito" },
    { display: "Rivera", value: "Rivera" },
    { display: "Saladoblanco", value: "Saladoblanco" },
    { display: "San agustín", value: "San agustín" },
    { display: "Santa maría", value: "Santa maría" },
    { display: "Suaza", value: "Suaza" },
    { display: "Tarqui", value: "Tarqui" },
    { display: "Tesalia", value: "Tesalia" },
    { display: "Tello", value: "Tello" },
    { display: "Teruel", value: "Teruel" },
    { display: "Timaná", value: "Timaná" },
    { display: "Villavieja", value: "Villavieja" },
    { display: "Yaguará", value: "Yaguará" }];

  var la_guajira = [
    { display: "Riohacha", value: "Riohacha" },
    { display: "Albania", value: "Albania" },
    { display: "Barrancas", value: "Barrancas" },
    { display: "Dibulla", value: "Dibulla" },
    { display: "Distracción", value: "Distracción" },
    { display: "El molino", value: "El molino" },
    { display: "Fonseca", value: "Fonseca" },
    { display: "Hatonuevo", value: "Hatonuevo" },
    { display: "La jagua del pilar", value: "La jagua del pilar" },
    { display: "Maicao", value: "Maicao" },
    { display: "Manaure", value: "Manaure" },
    { display: "San juan del cesar", value: "San juan del cesar" },
    { display: "Uribia", value: "Uribia" },
    { display: "Urumita", value: "Urumita" },
    { display: "Villanueva", value: "Villanueva" }];

  var magdalena = [
    { display: "Santa marta", value: "Santa marta" },
    { display: "Algarrobo", value: "Algarrobo" },
    { display: "Aracataca", value: "Aracataca" },
    { display: "Ariguaní", value: "Ariguaní" },
    { display: "Cerro de san antonio", value: "Cerro de san antonio" },
    { display: "Chivolo", value: "Chivolo" },
    { display: "Ciénaga", value: "Ciénaga" },
    { display: "Concordia", value: "Concordia" },
    { display: "El banco", value: "El banco" },
    { display: "El piñón", value: "El piñón" },
    { display: "El retén", value: "El retén" },
    { display: "Fundación", value: "Fundación" },
    { display: "Guamal", value: "Guamal" },
    { display: "Nueva granada", value: "Nueva granada" },
    { display: "Pedraza", value: "Pedraza" },
    { display: "Pijiño del carmen", value: "Pijiño del carmen" },
    { display: "Pivijay", value: "Pivijay" },
    { display: "Plato", value: "Plato" },
    { display: "Puebloviejo", value: "Puebloviejo" },
    { display: "Remolino", value: "Remolino" },
    { display: "Sabanas de san ángel", value: "Sabanas de san ángel" },
    { display: "Salamina", value: "Salamina" },
    { display: "San sebastián de buenavista", value: "San sebastián de buenavista" },
    { display: "San zenón", value: "San zenón" },
    { display: "Santa ana", value: "Santa ana" },
    { display: "Santa bárbara de pinto", value: "Santa bárbara de pinto" },
    { display: "Sitionuevo", value: "Sitionuevo" },
    { display: "Tenerife", value: "Tenerife" },
    { display: "Zapayán", value: "Zapayán" },
    { display: "Zona bananera", value: "Zona bananera" }];

  var meta = [
    { display: "Villavicencio", value: "Villavicencio" },
    { display: "Acacías", value: "Acacías" },
    { display: "Barranca de upía", value: "Barranca de upía" },
    { display: "Cabuyaro", value: "Cabuyaro" },
    { display: "Castilla la nueva", value: "Castilla la nueva" },
    { display: "Cubarral", value: "Cubarral" },
    { display: "Cumaral", value: "Cumaral" },
    { display: "El calvario", value: "El calvario" },
    { display: "El castillo", value: "El castillo" },
    { display: "El dorado", value: "El dorado" },
    { display: "Fuente de oro", value: "Fuente de oro" },
    { display: "Granada", value: "Granada" },
    { display: "Guamal", value: "Guamal" },
    { display: "Mapiripán", value: "Mapiripán" },
    { display: "Mesetas", value: "Mesetas" },
    { display: "La macarena", value: "La macarena" },
    { display: "Uribe", value: "Uribe" },
    { display: "Lejanías", value: "Lejanías" },
    { display: "Puerto concordia", value: "Puerto concordia" },
    { display: "Puerto gaitán", value: "Puerto gaitán" },
    { display: "Puerto lópez", value: "Puerto lópez" },
    { display: "Puerto lleras", value: "Puerto lleras" },
    { display: "Puerto rico", value: "Puerto rico" },
    { display: "Restrepo", value: "Restrepo" },
    { display: "San carlos de guaroa", value: "San carlos de guaroa" },
    { display: "San juan de arama", value: "San juan de arama" },
    { display: "San juanito", value: "San juanito" },
    { display: "San martín", value: "San martín" },
    { display: "Vistahermosa", value: "Vistahermosa" }];

  var nariño = [
    { display: "Pasto", value: "Pasto" },
    { display: "Albán", value: "Albán" },
    { display: "Aldana", value: "Aldana" },
    { display: "Ancuyá", value: "Ancuyá" },
    { display: "Arboleda", value: "Arboleda" },
    { display: "Barbacoas", value: "Barbacoas" },
    { display: "Belén", value: "Belén" },
    { display: "Buesaco", value: "Buesaco" },
    { display: "Colón", value: "Colón" },
    { display: "Consacá", value: "Consacá" },
    { display: "Contadero", value: "Contadero" },
    { display: "Córdoba", value: "Córdoba" },
    { display: "Cuaspúd", value: "Cuaspúd" },
    { display: "Cumbal", value: "Cumbal" },
    { display: "Cumbitara", value: "Cumbitara" },
    { display: "Chachagüí", value: "Chachagüí" },
    { display: "El charco", value: "El charco" },
    { display: "El peñol", value: "El peñol" },
    { display: "El rosario", value: "El rosario" },
    { display: "El tablón de gómez", value: "El tablón de gómez" },
    { display: "El tambo", value: "El tambo" },
    { display: "Funes", value: "Funes" },
    { display: "Guachucal", value: "Guachucal" },
    { display: "Guaitarilla", value: "Guaitarilla" },
    { display: "Gualmatán", value: "Gualmatán" },
    { display: "Iles", value: "Iles" },
    { display: "Imués", value: "Imués" },
    { display: "Ipiales", value: "Ipiales" },
    { display: "La cruz", value: "La cruz" },
    { display: "La florida", value: "La florida" },
    { display: "La llanada", value: "La llanada" },
    { display: "La tola", value: "La tola" },
    { display: "La unión", value: "La unión" },
    { display: "Leiva", value: "Leiva" },
    { display: "Linares", value: "Linares" },
    { display: "Los andes", value: "Los andes" },
    { display: "Magüí", value: "Magüí" },
    { display: "Mallama", value: "Mallama" },
    { display: "Mosquera", value: "Mosquera" },
    { display: "Nariño", value: "Nariño" },
    { display: "Olaya herrera", value: "Olaya herrera" },
    { display: "Ospina", value: "Ospina" },
    { display: "Francisco pizarro", value: "Francisco pizarro" },
    { display: "Policarpa", value: "Policarpa" },
    { display: "Potosí", value: "Potosí" },
    { display: "Providencia", value: "Providencia" },
    { display: "Puerres", value: "Puerres" },
    { display: "Pupiales", value: "Pupiales" },
    { display: "Ricaurte", value: "Ricaurte" },
    { display: "Roberto payán", value: "Roberto payán" },
    { display: "Samaniego", value: "Samaniego" },
    { display: "Sandoná", value: "Sandoná" },
    { display: "San bernardo", value: "San bernardo" },
    { display: "San lorenzo", value: "San lorenzo" },
    { display: "San pablo", value: "San pablo" },
    { display: "San pedro de cartago", value: "San pedro de cartago" },
    { display: "Santa bárbara", value: "Santa bárbara" },
    { display: "Santacruz", value: "Santacruz" },
    { display: "Sapuyes", value: "Sapuyes" },
    { display: "Taminango", value: "Taminango" },
    { display: "Tangua", value: "Tangua" },
    { display: "San andrés de tumaco", value: "San andrés de tumaco" },
    { display: "Túquerres", value: "Túquerres" },
    { display: "Yacuanquer", value: "Yacuanquer" }];

  var norte_de_santander = [
    { display: "Cúcuta", value: "Cúcuta" },
    { display: "Ábrego", value: "Ábrego" },
    { display: "Arboledas", value: "Arboledas" },
    { display: "Bochalema", value: "Bochalema" },
    { display: "Bucarasica", value: "Bucarasica" },
    { display: "Cácota", value: "Cácota" },
    { display: "Cáchira", value: "Cáchira" },
    { display: "Chinácota", value: "Chinácota" },
    { display: "Chitagá", value: "Chitagá" },
    { display: "Convención", value: "Convención" },
    { display: "Cucutilla", value: "Cucutilla" },
    { display: "Durania", value: "Durania" },
    { display: "El carmen", value: "El carmen" },
    { display: "El tarra", value: "El tarra" },
    { display: "El zulia", value: "El zulia" },
    { display: "Gramalote", value: "Gramalote" },
    { display: "Hacarí", value: "Hacarí" },
    { display: "Herrán", value: "Herrán" },
    { display: "Labateca", value: "Labateca" },
    { display: "La esperanza", value: "La esperanza" },
    { display: "La playa", value: "La playa" },
    { display: "Los patios", value: "Los patios" },
    { display: "Lourdes", value: "Lourdes" },
    { display: "Mutiscua", value: "Mutiscua" },
    { display: "Ocaña", value: "Ocaña" },
    { display: "Pamplona", value: "Pamplona" },
    { display: "Pamplonita", value: "Pamplonita" },
    { display: "Puerto santander", value: "Puerto santander" },
    { display: "Ragonvalia", value: "Ragonvalia" },
    { display: "Salazar", value: "Salazar" },
    { display: "San calixto", value: "San calixto" },
    { display: "San cayetano", value: "San cayetano" },
    { display: "Santiago", value: "Santiago" },
    { display: "Sardinata", value: "Sardinata" },
    { display: "Silos", value: "Silos" },
    { display: "Teorama", value: "Teorama" },
    { display: "Tibú", value: "Tibú" },
    { display: "Toledo", value: "Toledo" },
    { display: "Villa caro", value: "Villa caro" },
    { display: "Villa del rosario", value: "Villa del rosario" }];

  var quindio = [
    { display: "Armenia", value: "Armenia" },
    { display: "Buenavista", value: "Buenavista" },
    { display: "Calarcá", value: "Calarcá" },
    { display: "Circasia", value: "Circasia" },
    { display: "Córdoba", value: "Córdoba" },
    { display: "Filandia", value: "Filandia" },
    { display: "Génova", value: "Génova" },
    { display: "La tebaida", value: "La tebaida" },
    { display: "Montenegro", value: "Montenegro" },
    { display: "Pijao", value: "Pijao" },
    { display: "Quimbaya", value: "Quimbaya" },
    { display: "Salento", value: "Salento" }];

  var risaralda = [
    { display: "Pereira", value: "Pereira" },
    { display: "Apía", value: "Apía" },
    { display: "Balboa", value: "Balboa" },
    { display: "Belén de umbría", value: "Belén de umbría" },
    { display: "Dosquebradas", value: "Dosquebradas" },
    { display: "Guática", value: "Guática" },
    { display: "La celia", value: "La celia" },
    { display: "La virginia", value: "La virginia" },
    { display: "Marsella", value: "Marsella" },
    { display: "Mistrató", value: "Mistrató" },
    { display: "Pueblo rico", value: "Pueblo rico" },
    { display: "Quinchía", value: "Quinchía" },
    { display: "Santa rosa de cabal", value: "Santa rosa de cabal" },
    { display: "Santuario", value: "Santuario" }];

  var santander = [
    { display: "Bucaramanga", value: "Bucaramanga" },
    { display: "Aguada", value: "Aguada" },
    { display: "Albania", value: "Albania" },
    { display: "Aratoca", value: "Aratoca" },
    { display: "Barbosa", value: "Barbosa" },
    { display: "Barichara", value: "Barichara" },
    { display: "Barrancabermeja", value: "Barrancabermeja" },
    { display: "Betulia", value: "Betulia" },
    { display: "Bolívar", value: "Bolívar" },
    { display: "Cabrera", value: "Cabrera" },
    { display: "California", value: "California" },
    { display: "Capitanejo", value: "Capitanejo" },
    { display: "Carcasí", value: "Carcasí" },
    { display: "Cepitá", value: "Cepitá" },
    { display: "Cerrito", value: "Cerrito" },
    { display: "Charalá", value: "Charalá" },
    { display: "Charta", value: "Charta" },
    { display: "Chima", value: "Chima" },
    { display: "Chipatá", value: "Chipatá" },
    { display: "Cimitarra", value: "Cimitarra" },
    { display: "Concepción", value: "Concepción" },
    { display: "Confines", value: "Confines" },
    { display: "Contratación", value: "Contratación" },
    { display: "Coromoro", value: "Coromoro" },
    { display: "Curití", value: "Curití" },
    { display: "El carmen de chucurí", value: "El carmen de chucurí" },
    { display: "El guacamayo", value: "El guacamayo" },
    { display: "El peñón", value: "El peñón" },
    { display: "El playón", value: "El playón" },
    { display: "Encino", value: "Encino" },
    { display: "Enciso", value: "Enciso" },
    { display: "Florián", value: "Florián" },
    { display: "Floridablanca", value: "Floridablanca" },
    { display: "Galán", value: "Galán" },
    { display: "Gámbita", value: "Gámbita" },
    { display: "Girón", value: "Girón" },
    { display: "Guaca", value: "Guaca" },
    { display: "Guadalupe", value: "Guadalupe" },
    { display: "Guapotá", value: "Guapotá" },
    { display: "Guavatá", value: "Guavatá" },
    { display: "Güepsa", value: "Güepsa" },
    { display: "Hato", value: "Hato" },
    { display: "Jesús maría", value: "Jesús maría" },
    { display: "Jordán", value: "Jordán" },
    { display: "La belleza", value: "La belleza" },
    { display: "Landázuri", value: "Landázuri" },
    { display: "La paz", value: "La paz" },
    { display: "Lebrija", value: "Lebrija" },
    { display: "Los santos", value: "Los santos" },
    { display: "Macaravita", value: "Macaravita" },
    { display: "Málaga", value: "Málaga" },
    { display: "Matanza", value: "Matanza" },
    { display: "Mogotes", value: "Mogotes" },
    { display: "Molagavita", value: "Molagavita" },
    { display: "Ocamonte", value: "Ocamonte" },
    { display: "Oiba", value: "Oiba" },
    { display: "Onzaga", value: "Onzaga" },
    { display: "Palmar", value: "Palmar" },
    { display: "Palmas del socorro", value: "Palmas del socorro" },
    { display: "Páramo", value: "Páramo" },
    { display: "Piedecuesta", value: "Piedecuesta" },
    { display: "Pinchote", value: "Pinchote" },
    { display: "Puente nacional", value: "Puente nacional" },
    { display: "Puerto parra", value: "Puerto parra" },
    { display: "Puerto wilches", value: "Puerto wilches" },
    { display: "Rionegro", value: "Rionegro" },
    { display: "Sabana de torres", value: "Sabana de torres" },
    { display: "San andrés", value: "San andrés" },
    { display: "San benito", value: "San benito" },
    { display: "San gil", value: "San gil" },
    { display: "San joaquín", value: "San joaquín" },
    { display: "San josé de miranda", value: "San josé de miranda" },
    { display: "San miguel", value: "San miguel" },
    { display: "San vicente de chucurí", value: "San vicente de chucurí" },
    { display: "Santa bárbara", value: "Santa bárbara" },
    { display: "Santa helena del opón", value: "Santa helena del opón" },
    { display: "Simacota", value: "Simacota" },
    { display: "Socorro", value: "Socorro" },
    { display: "Suaita", value: "Suaita" },
    { display: "Sucre", value: "Sucre" },
    { display: "Suratá", value: "Suratá" },
    { display: "Tona", value: "Tona" },
    { display: "Valle de san josé", value: "Valle de san josé" },
    { display: "Vélez", value: "Vélez" },
    { display: "Vetas", value: "Vetas" },
    { display: "Villanueva", value: "Villanueva" },
    { display: "Zapatoca", value: "Zapatoca" }];

  var sucre = [
    { display: "Sincelejo", value: "Sincelejo" },
    { display: "Buenavista", value: "Buenavista" },
    { display: "Caimito", value: "Caimito" },
    { display: "Colosó", value: "Colosó" },
    { display: "Corozal", value: "Corozal" },
    { display: "Coveñas", value: "Coveñas" },
    { display: "Chalán", value: "Chalán" },
    { display: "El roble", value: "El roble" },
    { display: "Galeras", value: "Galeras" },
    { display: "Guaranda", value: "Guaranda" },
    { display: "La unión", value: "La unión" },
    { display: "Los palmitos", value: "Los palmitos" },
    { display: "Majagual", value: "Majagual" },
    { display: "Morroa", value: "Morroa" },
    { display: "Ovejas", value: "Ovejas" },
    { display: "Palmito", value: "Palmito" },
    { display: "Sampués", value: "Sampués" },
    { display: "San benito abad", value: "San benito abad" },
    { display: "San juan de betulia", value: "San juan de betulia" },
    { display: "San marcos", value: "San marcos" },
    { display: "San onofre", value: "San onofre" },
    { display: "San pedro", value: "San pedro" },
    { display: "San luis de sincé", value: "San luis de sincé" },
    { display: "Sucre", value: "Sucre" },
    { display: "Santiago de tolú", value: "Santiago de tolú" },
    { display: "Tolú viejo", value: "Tolú viejo" }];

  var tolima = [
    { display: "Ibagué", value: "Ibagué" },
    { display: "Alpujarra", value: "Alpujarra" },
    { display: "Alvarado", value: "Alvarado" },
    { display: "Ambalema", value: "Ambalema" },
    { display: "Anzoátegui", value: "Anzoátegui" },
    { display: "Armero guayabal", value: "Armero guayabal" },
    { display: "Ataco", value: "Ataco" },
    { display: "Cajamarca", value: "Cajamarca" },
    { display: "Carmen de apicalá", value: "Carmen de apicalá" },
    { display: "Casabianca", value: "Casabianca" },
    { display: "Chaparral", value: "Chaparral" },
    { display: "Coello", value: "Coello" },
    { display: "Coyaima", value: "Coyaima" },
    { display: "Cunday", value: "Cunday" },
    { display: "Dolores", value: "Dolores" },
    { display: "Espinal", value: "Espinal" },
    { display: "Falan", value: "Falan" },
    { display: "Flandes", value: "Flandes" },
    { display: "Fresno", value: "Fresno" },
    { display: "Guamo", value: "Guamo" },
    { display: "Herveo", value: "Herveo" },
    { display: "Honda", value: "Honda" },
    { display: "Icononzo", value: "Icononzo" },
    { display: "Lérida", value: "Lérida" },
    { display: "Líbano", value: "Líbano" },
    { display: "San sebastián de mariquita", value: "San sebastián de mariquita" },
    { display: "Melgar", value: "Melgar" },
    { display: "Murillo", value: "Murillo" },
    { display: "Natagaima", value: "Natagaima" },
    { display: "Ortega", value: "Ortega" },
    { display: "Palocabildo", value: "Palocabildo" },
    { display: "Piedras", value: "Piedras" },
    { display: "Planadas", value: "Planadas" },
    { display: "Prado", value: "Prado" },
    { display: "Purificación", value: "Purificación" },
    { display: "Rioblanco", value: "Rioblanco" },
    { display: "Roncesvalles", value: "Roncesvalles" },
    { display: "Rovira", value: "Rovira" },
    { display: "Saldaña", value: "Saldaña" },
    { display: "San antonio", value: "San antonio" },
    { display: "San luis", value: "San luis" },
    { display: "Santa isabel", value: "Santa isabel" },
    { display: "Suárez", value: "Suárez" },
    { display: "Valle de san juan", value: "Valle de san juan" },
    { display: "Venadillo", value: "Venadillo" },
    { display: "Villahermosa", value: "Villahermosa" },
    { display: "Villarrica", value: "Villarrica" }];

  var valle_del_cauca = [
    { display: "Cali", value: "Cali" },
    { display: "Alcalá", value: "Alcalá" },
    { display: "Andalucía", value: "Andalucía" },
    { display: "Ansermanuevo", value: "Ansermanuevo" },
    { display: "Argelia", value: "Argelia" },
    { display: "Bolívar", value: "Bolívar" },
    { display: "Buenaventura", value: "Buenaventura" },
    { display: "Guadalajara de buga", value: "Guadalajara de buga" },
    { display: "Bugalagrande", value: "Bugalagrande" },
    { display: "Caicedonia", value: "Caicedonia" },
    { display: "Calima", value: "Calima" },
    { display: "Candelaria", value: "Candelaria" },
    { display: "Cartago", value: "Cartago" },
    { display: "Dagua", value: "Dagua" },
    { display: "El águila", value: "El águila" },
    { display: "El cairo", value: "El cairo" },
    { display: "El cerrito", value: "El cerrito" },
    { display: "El dovio", value: "El dovio" },
    { display: "Florida", value: "Florida" },
    { display: "Ginebra", value: "Ginebra" },
    { display: "Guacarí", value: "Guacarí" },
    { display: "Jamundí", value: "Jamundí" },
    { display: "La cumbre", value: "La cumbre" },
    { display: "La unión", value: "La unión" },
    { display: "La victoria", value: "La victoria" },
    { display: "Obando", value: "Obando" },
    { display: "Palmira", value: "Palmira" },
    { display: "Pradera", value: "Pradera" },
    { display: "Restrepo", value: "Restrepo" },
    { display: "Riofrío", value: "Riofrío" },
    { display: "Roldanillo", value: "Roldanillo" },
    { display: "San pedro", value: "San pedro" },
    { display: "Sevilla", value: "Sevilla" },
    { display: "Toro", value: "Toro" },
    { display: "Trujillo", value: "Trujillo" },
    { display: "Tuluá", value: "Tuluá" },
    { display: "Ulloa", value: "Ulloa" },
    { display: "Versalles", value: "Versalles" },
    { display: "Vijes", value: "Vijes" },
    { display: "Yotoco", value: "Yotoco" },
    { display: "Yumbo", value: "Yumbo" },
    { display: "Zarzal", value: "Zarzal" }];

  var arauca = [
    { display: "Arauca", value: "Arauca" },
    { display: "Arauquita", value: "Arauquita" },
    { display: "Cravo norte", value: "Cravo norte" },
    { display: "Fortul", value: "Fortul" },
    { display: "Puerto rondón", value: "Puerto rondón" },
    { display: "Saravena", value: "Saravena" },
    { display: "Tame", value: "Tame" }];

  var casanare = [
    { display: "Yopal", value: "Yopal" },
    { display: "Aguazul", value: "Aguazul" },
    { display: "Chámeza", value: "Chámeza" },
    { display: "Hato corozal", value: "Hato corozal" },
    { display: "La salina", value: "La salina" },
    { display: "Maní", value: "Maní" },
    { display: "Monterrey", value: "Monterrey" },
    { display: "Nunchía", value: "Nunchía" },
    { display: "Orocué", value: "Orocué" },
    { display: "Paz de ariporo", value: "Paz de ariporo" },
    { display: "Pore", value: "Pore" },
    { display: "Recetor", value: "Recetor" },
    { display: "Sabanalarga", value: "Sabanalarga" },
    { display: "Sácama", value: "Sácama" },
    { display: "San luis de palenque", value: "San luis de palenque" },
    { display: "Támara", value: "Támara" },
    { display: "Tauramena", value: "Tauramena" },
    { display: "Trinidad", value: "Trinidad" },
    { display: "Villanueva", value: "Villanueva" }];

  var putumayo = [
    { display: "Mocoa", value: "Mocoa" },
    { display: "Colón", value: "Colón" },
    { display: "Orito", value: "Orito" },
    { display: "Puerto asís", value: "Puerto asís" },
    { display: "Puerto caicedo", value: "Puerto caicedo" },
    { display: "Puerto guzmán", value: "Puerto guzmán" },
    { display: "Puerto leguízamo", value: "Puerto leguízamo" },
    { display: "Sibundoy", value: "Sibundoy" },
    { display: "San francisco", value: "San francisco" },
    { display: "San miguel", value: "San miguel" },
    { display: "Santiago", value: "Santiago" },
    { display: "Valle del guamuez", value: "Valle del guamuez" },
    { display: "Villagarzón", value: "Villagarzón" }];

  var san_andrés_y_providencia = [
    { display: "San andrés", value: "San andrés" },
    { display: "Providencia", value: "Providencia" }];

  var amazonas = [
    { display: "Leticia", value: "Leticia" },
    { display: "Puerto nariño", value: "Puerto nariño" }];

  var guainía = [
    { display: "Inírida", value: "Inírida" }];

  var guaviare = [
    { display: "San josé del guaviare", value: "San josé del guaviare" },
    { display: "Calamar", value: "Calamar" },
    { display: "El retorno", value: "El retorno" },
    { display: "Miraflores", value: "Miraflores" }];

  var vaupés = [
    { display: "Mitú", value: "Mitú" },
    { display: "Carurú", value: "Carurú" },
    { display: "Taraira", value: "Taraira" }];

  var vichada = [
    { display: "Puerto carreño", value: "Puerto carreño" },
    { display: "La primavera", value: "La primavera" },
    { display: "Santa rosalía", value: "Santa rosalía" },
    { display: "Cumaribo", value: "Cumaribo" }];

    /*** MUNICIPIO RESIDENCIA ***/
    $("#usp-custom-departamento-de-residencia").change(function () {
      var parent_residencia = $(this).val(); //get option value from parent
  
      switch (parent_residencia) { //using switch compare selected option and populate child
        case 'Amazonas':
          list_residencia(amazonas);
          break;
        case 'Antioquía':
          list_residencia(antioquía);
          break;
        case 'Arauca':
          list_residencia(arauca);
          break;
        case 'Atlántico':
          list_residencia(atlántico);
          break;
        case 'Bolívar':
          list_residencia(bolívar);
          break;
        case 'Boyacá':
          list_residencia(boyacá);
          break;
        case 'Caldas':
          list_residencia(caldas);
          break;
        case 'Caquetá':
          list_residencia(caquetá);
          break;
        case 'Casanare':
          list_residencia(casanare);
          break;
        case 'Cauca':
          list_residencia(cauca);
          break;
        case 'Cesar':
          list_residencia(cesar);
          break;
        case 'Chocó':
          list_residencia(chocó);
          break;
        case 'Córdoba':
          list_residencia(córdoba);
          break;
        case 'Cundinamarca':
          list_residencia(cundinamarca);
          break;
        case 'Guainía':
          list_residencia(guainía);
          break;
        case 'Guaviare':
          list_residencia(guaviare);
          break;
        case 'Huila':
          list_residencia(huila);
          break;
        case 'La Guajira':
          list_residencia(la_guajira);
          break;
        case 'Magdalena':
          list_residencia(magdalena);
          break;
        case 'Meta':
          list_residencia(meta);
          break;
        case 'Nariño':
          list_residencia(nariño);
          break;
        case 'Norte de Santander':
          list_residencia(norte_de_santander);
          break;
        case 'Putumayo':
          list_residencia(putumayo);
          break;
        case 'Quindío':
          list_residencia(quindio);
          break;
        case 'Risaralda':
          list_residencia(risaralda);
          break;
        case 'San Andrés y Providencia':
          list_residencia(san_andrés_y_providencia);
          break;
        case 'Santander':
          list_residencia(santander);
          break;
        case 'Sucre':
          list_residencia(sucre);
          break;
        case 'Tolima':
          list_residencia(tolima);
          break;
        case 'Valle del Cauca':
          list_residencia(valle_del_cauca);
          break;
        case 'Vaupés':
          list_residencia(vaupés);
          break;
        case 'Vichada':
          list_residencia(vichada);
          break;
  
        default: //default child option is blank
          $("#usp-custom-municipio-ciudad").html('');
          break;
      }
    });
  
    //function to populate child select box
    function list_residencia(array_list) {
      $("#usp-custom-municipio-ciudad").html(""); //reset child options
     // $("#usp-custom-municipio-ciudad").append("<option value='' disabled selected>Seleccionar..</option>");
      $(array_list).each(function (i) { //populate child options
        $("#usp-custom-municipio-ciudad").append("<option value=\"" + array_list[i].value + "\">" + array_list[i].display + "</option>");
      });
    }
  
  });