# Generated by Django 5.1 on 2024-09-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairsPost', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ferias',
        ),
    ]
