IMGBB_API_URL = "https://api.imgbb.com/1/upload"

DEPARTAMENTOS = [
        ('Amazonas', 'Amazonas'),
        ('Antioquía', 'Antioquía'),
        ('Arauca', 'Arauca'),
        ('Atlántico', 'Atlántico'),
        ('Bolívar', 'Bolívar'),
        ('Boyacá', 'Boyacá'),
        ('Caldas', 'Caldas'),
        ('Caquetá', 'Caquetá'),
        ('Casanare', 'Casanare'),
        ('Cauca', 'Cauca'),
        ('Cesar', 'Cesar'),
        ('Chocó', 'Chocó'),
        ('Córdoba', 'Córdoba'),
        ('Cundinamarca', 'Cundinamarca'),
        ('Guainía', 'Guainía'),
        ('Guaviare', 'Guaviare'),
        ('Huila', 'Huila'),
        ('La Guajira', 'La Guajira'),
        ('Magdalena', 'Magdalena'),
        ('Meta', 'Meta'),
        ('Nariño', 'Nariño'),
        ('Norte de Santander', 'Norte de Santander'),
        ('Putumayo', 'Putumayo'),
        ('Quindío', 'Quindío'),
        ('Risaralda', 'Risaralda'),
        ('San Andrés y Providencia', 'San Andrés y Providencia'),
        ('Santander', 'Santander'),
        ('Sucre', 'Sucre'),
        ('Tolima', 'Tolima'),
        ('Valle del Cauca', 'Valle del Cauca'),
        ('Vaupés', 'Vaupés'),
        ('Vichada', 'Vichada'),
    ]

MUNICIPIOS = [ ('Medellín', 'Medellín'),
('Abejorral', 'Abejorral'),
('Abriaquí', 'Abriaquí'),
('Alejandría', 'Alejandría'),
('Amagá', 'Amagá'),
('Amalfi', 'Amalfi'),
('Andes', 'Andes'),
('Angelópolis', 'Angelópolis'),
('Angostura', 'Angostura'),
('Anorí', 'Anorí'),
('Santa fé de antioquia', 'Santa fé de antioquia'),
('Anzá', 'Anzá'),
('Apartadó', 'Apartadó'),
('Arboletes', 'Arboletes'),
('Argelia', 'Argelia'),
('Armenia', 'Armenia'),
('Barbosa', 'Barbosa'),
('Belmira', 'Belmira'),
('Bello', 'Bello'),
('Betania', 'Betania'),
('Betulia', 'Betulia'),
('Ciudad bolívar', 'Ciudad bolívar'),
('Briceño', 'Briceño'),
('Buriticá', 'Buriticá'),
('Cáceres', 'Cáceres'),
('Caicedo', 'Caicedo'),
('Caldas', 'Caldas'),
('Campamento', 'Campamento'),
('Cañasgordas', 'Cañasgordas'),
('Caracolí', 'Caracolí'),
('Caramanta', 'Caramanta'),
('Carepa', 'Carepa'),
('El carmen de viboral', 'El carmen de viboral'),
('Carolina', 'Carolina'),
('Caucasia', 'Caucasia'),
('Chigorodó', 'Chigorodó'),
('Cisneros', 'Cisneros'),
('Cocorná', 'Cocorná'),
('Concepción', 'Concepción'),
('Concordia', 'Concordia'),
('Copacabana', 'Copacabana'),
('Dabeiba', 'Dabeiba'),
('Donmatías', 'Donmatías'),
('Ebéjico', 'Ebéjico'),
('El bagre', 'El bagre'),
('Entrerríos', 'Entrerríos'),
('Envigado', 'Envigado'),
('Fredonia', 'Fredonia'),
('Frontino', 'Frontino'),
('Giraldo', 'Giraldo'),
('Girardota', 'Girardota'),
('Gómez plata', 'Gómez plata'),
('Granada', 'Granada'),
('Guadalupe', 'Guadalupe'),
('Guarne', 'Guarne'),
('Guatapé', 'Guatapé'),
('Heliconia', 'Heliconia'),
('Hispania', 'Hispania'),
('Itagüí', 'Itagüí'),
('Ituango', 'Ituango'),
('Jardín', 'Jardín'),
('Jericó', 'Jericó'),
('La ceja', 'La ceja'),
('La estrella', 'La estrella'),
('La pintada', 'La pintada'),
('La unión', 'La unión'),
('Liborina', 'Liborina'),
('Maceo', 'Maceo'),
('Marinilla', 'Marinilla'),
('Montebello', 'Montebello'),
('Murindó', 'Murindó'),
('Mutatá', 'Mutatá'),
('Nariño', 'Nariño'),
('Necoclí', 'Necoclí'),
('Nechí', 'Nechí'),
('Olaya', 'Olaya'),
('Peñol', 'Peñol'),
('Peque', 'Peque'),
('Pueblorrico', 'Pueblorrico'),
('Puerto berrío', 'Puerto berrío'),
('Puerto nare', 'Puerto nare'),
('Puerto triunfo', 'Puerto triunfo'),
('Remedios', 'Remedios'),
('Retiro', 'Retiro'),
('Rionegro', 'Rionegro'),
('Sabanalarga', 'Sabanalarga'),
('Sabaneta', 'Sabaneta'),
('Salgar', 'Salgar'),
('San andrés de cuerquía', 'San andrés de cuerquía'),
('San carlos', 'San carlos'),
('San francisco', 'San francisco'),
('San jerónimo', 'San jerónimo'),
('San josé de la montaña', 'San josé de la montaña'),
('San juan de urabá', 'San juan de urabá'),
('San luis', 'San luis'),
('San pedro de los milagros', 'San pedro de los milagros'),
('San pedro de urabá', 'San pedro de urabá'),
('San rafael', 'San rafael'),
('San roque', 'San roque'),
('San vicente ferrer', 'San vicente ferrer'),
('Santa bárbara', 'Santa bárbara'),
('Santa rosa de osos', 'Santa rosa de osos'),
('Santo domingo', 'Santo domingo'),
('El santuario', 'El santuario'),
('Segovia', 'Segovia'),
('Sonsón', 'Sonsón'),
('Sopetrán', 'Sopetrán'),
('Támesis', 'Támesis'),
('Tarazá', 'Tarazá'),
('Tarso', 'Tarso'),
('Titiribí', 'Titiribí'),
('Toledo', 'Toledo'),
('Turbo', 'Turbo'),
('Uramita', 'Uramita'),
('Urrao', 'Urrao'),
('Valdivia', 'Valdivia'),
('Valparaíso', 'Valparaíso'),
('Vegachí', 'Vegachí'),
('Venecia', 'Venecia'),
('Vigía del fuerte', 'Vigía del fuerte'),
('Yalí', 'Yalí'),
('Yarumal', 'Yarumal'),
('Yolombó', 'Yolombó'),
('Yondó', 'Yondó'),
('Zaragoza', 'Zaragoza'),
('Barranquilla', 'Barranquilla'),
('Baranoa', 'Baranoa'),
('Campo de la cruz', 'Campo de la cruz'),
('Candelaria', 'Candelaria'),
('Galapa', 'Galapa'),
('Juan de acosta', 'Juan de acosta'),
('Luruaco', 'Luruaco'),
('Malambo', 'Malambo'),
('Manatí', 'Manatí'),
('Palmar de varela', 'Palmar de varela'),
('Piojó', 'Piojó'),
('Polonuevo', 'Polonuevo'),
('Ponedera', 'Ponedera'),
('Puerto colombia', 'Puerto colombia'),
('Repelón', 'Repelón'),
('Sabanagrande', 'Sabanagrande'),
('Sabanalarga', 'Sabanalarga'),
('Santa lucía', 'Santa lucía'),
('Santo tomás', 'Santo tomás'),
('Soledad', 'Soledad'),
('Suan', 'Suan'),
('Tubará', 'Tubará'),
('Usiacurí', 'Usiacurí'),
('Cartagena de indias', 'Cartagena de indias'),
('Achí', 'Achí'),
('Altos del rosario', 'Altos del rosario'),
('Arenal', 'Arenal'),
('Arjona', 'Arjona'),
('Arroyohondo', 'Arroyohondo'),
('Barranco de loba', 'Barranco de loba'),
('Calamar', 'Calamar'),
('Cantagallo', 'Cantagallo'),
('Cicuco', 'Cicuco'),
('Córdoba', 'Córdoba'),
('Clemencia', 'Clemencia'),
('El carmen de bolívar', 'El carmen de bolívar'),
('El guamo', 'El guamo'),
('El peñón', 'El peñón'),
('Hatillo de loba', 'Hatillo de loba'),
('Magangué', 'Magangué'),
('Mahates', 'Mahates'),
('Margarita', 'Margarita'),
('María la baja', 'María la baja'),
('Montecristo', 'Montecristo'),
('Mompós', 'Mompós'),
('Morales', 'Morales'),
('Norosí', 'Norosí'),
('Pinillos', 'Pinillos'),
('Regidor', 'Regidor'),
('Río viejo', 'Río viejo'),
('San cristóbal', 'San cristóbal'),
('San estanislao', 'San estanislao'),
('San fernando', 'San fernando'),
('San jacinto', 'San jacinto'),
('San jacinto del cauca', 'San jacinto del cauca'),
('San juan nepomuceno', 'San juan nepomuceno'),
('San martín de loba', 'San martín de loba'),
('San pablo', 'San pablo'),
('Santa catalina', 'Santa catalina'),
('Santa rosa', 'Santa rosa'),
('Santa rosa del sur', 'Santa rosa del sur'),
('Simití', 'Simití'),
('Soplaviento', 'Soplaviento'),
('Talaigua nuevo', 'Talaigua nuevo'),
('Tiquisio', 'Tiquisio'),
('Turbaco', 'Turbaco'),
('Turbaná', 'Turbaná'),
('Villanueva', 'Villanueva'),
('Zambrano', 'Zambrano'),
('Tunja', 'Tunja'),
('Almeida', 'Almeida'),
('Aquitania', 'Aquitania'),
('Arcabuco', 'Arcabuco'),
('Belén', 'Belén'),
('Berbeo', 'Berbeo'),
('Betéitiva', 'Betéitiva'),
('Boavita', 'Boavita'),
('Boyacá', 'Boyacá'),
('Briceño', 'Briceño'),
('Buenavista', 'Buenavista'),
('Busbanzá', 'Busbanzá'),
('Caldas', 'Caldas'),
('Campohermoso', 'Campohermoso'),
('Cerinza', 'Cerinza'),
('Chinavita', 'Chinavita'),
('Chiquinquirá', 'Chiquinquirá'),
('Chiscas', 'Chiscas'),
('Chita', 'Chita'),
('Chitaraque', 'Chitaraque'),
('Chivatá', 'Chivatá'),
('Ciénega', 'Ciénega'),
('Cómbita', 'Cómbita'),
('Coper', 'Coper'),
('Corrales', 'Corrales'),
('Covarachía', 'Covarachía'),
('Cubará', 'Cubará'),
('Cucaita', 'Cucaita'),
('Cuítiva', 'Cuítiva'),
('Chíquiza', 'Chíquiza'),
('Chivor', 'Chivor'),
('Duitama', 'Duitama'),
('El cocuy', 'El cocuy'),
('El espino', 'El espino'),
('Firavitoba', 'Firavitoba'),
('Floresta', 'Floresta'),
('Gachantivá', 'Gachantivá'),
('Gámeza', 'Gámeza'),
('Garagoa', 'Garagoa'),
('Guacamayas', 'Guacamayas'),
('Guateque', 'Guateque'),
('Guayatá', 'Guayatá'),
('Güicán', 'Güicán'),
('Iza', 'Iza'),
('Jenesano', 'Jenesano'),
('Jericó', 'Jericó'),
('Labranzagrande', 'Labranzagrande'),
('La capilla', 'La capilla'),
('La victoria', 'La victoria'),
('La uvita', 'La uvita'),
('Villa de leyva', 'Villa de leyva'),
('Macanal', 'Macanal'),
('Maripí', 'Maripí'),
('Miraflores', 'Miraflores'),
('Mongua', 'Mongua'),
('Monguí', 'Monguí'),
('Moniquirá', 'Moniquirá'),
('Motavita', 'Motavita'),
('Muzo', 'Muzo'),
('Nobsa', 'Nobsa'),
('Nuevo colón', 'Nuevo colón'),
('Oicatá', 'Oicatá'),
('Otanche', 'Otanche'),
('Pachavita', 'Pachavita'),
('Páez', 'Páez'),
('Paipa', 'Paipa'),
('Pajarito', 'Pajarito'),
('Panqueba', 'Panqueba'),
('Pauna', 'Pauna'),
('Paya', 'Paya'),
('Paz de río', 'Paz de río'),
('Pesca', 'Pesca'),
('Pisba', 'Pisba'),
('Puerto boyacá', 'Puerto boyacá'),
('Quípama', 'Quípama'),
('Ramiriquí', 'Ramiriquí'),
('Ráquira', 'Ráquira'),
('Rondón', 'Rondón'),
('Saboyá', 'Saboyá'),
('Sáchica', 'Sáchica'),
('Samacá', 'Samacá'),
('San eduardo', 'San eduardo'),
('San josé de pare', 'San josé de pare'),
('San luis de gaceno', 'San luis de gaceno'),
('San mateo', 'San mateo'),
('San miguel de sema', 'San miguel de sema'),
('San pablo de borbur', 'San pablo de borbur'),
('Santana', 'Santana'),
('Santa maría', 'Santa maría'),
('Santa rosa de viterbo', 'Santa rosa de viterbo'),
('Santa sofía', 'Santa sofía'),
('Sativanorte', 'Sativanorte'),
('Sativasur', 'Sativasur'),
('Siachoque', 'Siachoque'),
('Soatá', 'Soatá'),
('Socotá', 'Socotá'),
('Socha', 'Socha'),
('Sogamoso', 'Sogamoso'),
('Somondoco', 'Somondoco'),
('Sora', 'Sora'),
('Sotaquirá', 'Sotaquirá'),
('Soracá', 'Soracá'),
('Susacón', 'Susacón'),
('Sutamarchán', 'Sutamarchán'),
('Sutatenza', 'Sutatenza'),
('Tasco', 'Tasco'),
('Tenza', 'Tenza'),
('Tibaná', 'Tibaná'),
('Tibasosa', 'Tibasosa'),
('Tinjacá', 'Tinjacá'),
('Tipacoque', 'Tipacoque'),
('Toca', 'Toca'),
('Togüí', 'Togüí'),
('Tópaga', 'Tópaga'),
('Tota', 'Tota'),
('Tununguá', 'Tununguá'),
('Turmequé', 'Turmequé'),
('Tuta', 'Tuta'),
('Tutazá', 'Tutazá'),
('Úmbita', 'Úmbita'),
('Ventaquemada', 'Ventaquemada'),
('Viracachá', 'Viracachá'),
('Zetaquira', 'Zetaquira'),
('Manizales', 'Manizales'),
('Aguadas', 'Aguadas'),
('Anserma', 'Anserma'),
('Aranzazu', 'Aranzazu'),
('Belalcázar', 'Belalcázar'),
('Chinchiná', 'Chinchiná'),
('Filadelfia', 'Filadelfia'),
('La dorada', 'La dorada'),
('La merced', 'La merced'),
('Manzanares', 'Manzanares'),
('Marmato', 'Marmato'),
('Marquetalia', 'Marquetalia'),
('Marulanda', 'Marulanda'),
('Neira', 'Neira'),
('Norcasia', 'Norcasia'),
('Pácora', 'Pácora'),
('Palestina', 'Palestina'),
('Pensilvania', 'Pensilvania'),
('Riosucio', 'Riosucio'),
('Risaralda', 'Risaralda'),
('Salamina', 'Salamina'),
('Samaná', 'Samaná'),
('San josé', 'San josé'),
('Supía', 'Supía'),
('Victoria', 'Victoria'),
('Villamaría', 'Villamaría'),
('Viterbo', 'Viterbo'),
('Florencia', 'Florencia'),
('Albania', 'Albania'),
('Belén de los andaquíes', 'Belén de los andaquíes'),
('Cartagena del chairá', 'Cartagena del chairá'),
('Curillo', 'Curillo'),
('El doncello', 'El doncello'),
('El paujíl', 'El paujíl'),
('La montañita', 'La montañita'),
('Milán', 'Milán'),
('Morelia', 'Morelia'),
('Puerto rico', 'Puerto rico'),
('San josé del fragua', 'San josé del fragua'),
('San vicente del caguán', 'San vicente del caguán'),
('Solano', 'Solano'),
('Solita', 'Solita'),
('Valparaíso', 'Valparaíso'),
('Popayán', 'Popayán'),
('Almaguer', 'Almaguer'),
('Argelia', 'Argelia'),
('Balboa', 'Balboa'),
('Bolívar', 'Bolívar'),
('Buenos aires', 'Buenos aires'),
('Cajibío', 'Cajibío'),
('Caldono', 'Caldono'),
('Caloto', 'Caloto'),
('Corinto', 'Corinto'),
('El tambo', 'El tambo'),
('Florencia', 'Florencia'),
('Guachené', 'Guachené'),
('Guapí', 'Guapí'),
('Inzá', 'Inzá'),
('Jambaló', 'Jambaló'),
('La sierra', 'La sierra'),
('La vega', 'La vega'),
('López de micay', 'López de micay'),
('Mercaderes', 'Mercaderes'),
('Miranda', 'Miranda'),
('Morales', 'Morales'),
('Padilla', 'Padilla'),
('Páez', 'Páez'),
('Patía', 'Patía'),
('Piamonte', 'Piamonte'),
('Piendamó', 'Piendamó'),
('Puerto tejada', 'Puerto tejada'),
('Puracé', 'Puracé'),
('Rosas', 'Rosas'),
('San sebastián', 'San sebastián'),
('Santander de quilichao', 'Santander de quilichao'),
('Santa rosa', 'Santa rosa'),
('Silvia', 'Silvia'),
('Sotara', 'Sotara'),
('Suárez', 'Suárez'),
('Sucre', 'Sucre'),
('Timbío', 'Timbío'),
('Timbiquí', 'Timbiquí'),
('Toribío', 'Toribío'),
('Totoró', 'Totoró'),
('Villa rica', 'Villa rica'),
('Valledupar', 'Valledupar'),
('Aguachica', 'Aguachica'),
('Agustín codazzi', 'Agustín codazzi'),
('Astrea', 'Astrea'),
('Becerril', 'Becerril'),
('Bosconia', 'Bosconia'),
('Chimichagua', 'Chimichagua'),
('Chiriguaná', 'Chiriguaná'),
('Curumaní', 'Curumaní'),
('El copey', 'El copey'),
('El paso', 'El paso'),
('Gamarra', 'Gamarra'),
('González', 'González'),
('La gloria', 'La gloria'),
('La jagua de ibirico', 'La jagua de ibirico'),
('Manaure balcón del cesar', 'Manaure balcón del cesar'),
('Pailitas', 'Pailitas'),
('Pelaya', 'Pelaya'),
('Pueblo bello', 'Pueblo bello'),
('Río de oro', 'Río de oro'),
('La paz', 'La paz'),
('San alberto', 'San alberto'),
('San diego', 'San diego'),
('San martín', 'San martín'),
('Tamalameque', 'Tamalameque'),
('Montería', 'Montería'),
('Ayapel', 'Ayapel'),
('Buenavista', 'Buenavista'),
('Canalete', 'Canalete'),
('Cereté', 'Cereté'),
('Chimá', 'Chimá'),
('Chinú', 'Chinú'),
('Ciénaga de oro', 'Ciénaga de oro'),
('Cotorra', 'Cotorra'),
('La apartada', 'La apartada'),
('Lorica', 'Lorica'),
('Los córdobas', 'Los córdobas'),
('Momil', 'Momil'),
('Montelíbano', 'Montelíbano'),
('Moñitos', 'Moñitos'),
('Planeta rica', 'Planeta rica'),
('Pueblo nuevo', 'Pueblo nuevo'),
('Puerto escondido', 'Puerto escondido'),
('Puerto libertador', 'Puerto libertador'),
('Purísima de la concepción', 'Purísima de la concepción'),
('Sahagún', 'Sahagún'),
('San andrés de sotavento', 'San andrés de sotavento'),
('San antero', 'San antero'),
('San bernardo del viento', 'San bernardo del viento'),
('San carlos', 'San carlos'),
('San josé de uré', 'San josé de uré'),
('San pelayo', 'San pelayo'),
('Tierralta', 'Tierralta'),
('Tuchín', 'Tuchín'),
('Valencia', 'Valencia'),
('Agua de dios', 'Agua de dios'),
('Albán', 'Albán'),
('Anapoima', 'Anapoima'),
('Anolaima', 'Anolaima'),
('Arbeláez', 'Arbeláez'),
('Beltrán', 'Beltrán'),
('Bituima', 'Bituima'),
('Bogotá, d.c.', 'Bogotá, d.c.'),
('Bojacá', 'Bojacá'),
('Cabrera', 'Cabrera'),
('Cachipay', 'Cachipay'),
('Cajicá', 'Cajicá'),
('Caparrapí', 'Caparrapí'),
('Cáqueza', 'Cáqueza'),
('Carmen de carupa', 'Carmen de carupa'),
('Chaguaní', 'Chaguaní'),
('Chía', 'Chía'),
('Chipaque', 'Chipaque'),
('Choachí', 'Choachí'),
('Chocontá', 'Chocontá'),
('Cogua', 'Cogua'),
('Cota', 'Cota'),
('Cucunubá', 'Cucunubá'),
('El colegio', 'El colegio'),
('El peñón', 'El peñón'),
('El rosal', 'El rosal'),
('Facatativá', 'Facatativá'),
('Fómeque', 'Fómeque'),
('Fosca', 'Fosca'),
('Funza', 'Funza'),
('Fúquene', 'Fúquene'),
('Fusagasugá', 'Fusagasugá'),
('Gachalá', 'Gachalá'),
('Gachancipá', 'Gachancipá'),
('Gachetá', 'Gachetá'),
('Gama', 'Gama'),
('Girardot', 'Girardot'),
('Granada', 'Granada'),
('Guachetá', 'Guachetá'),
('Guaduas', 'Guaduas'),
('Guasca', 'Guasca'),
('Guataquí', 'Guataquí'),
('Guatavita', 'Guatavita'),
('Guayabal de síquima', 'Guayabal de síquima'),
('Guayabetal', 'Guayabetal'),
('Gutiérrez', 'Gutiérrez'),
('Jerusalén', 'Jerusalén'),
('Junín', 'Junín'),
('La calera', 'La calera'),
('La mesa', 'La mesa'),
('La palma', 'La palma'),
('La peña', 'La peña'),
('La vega', 'La vega'),
('Lenguazaque', 'Lenguazaque'),
('Machetá', 'Machetá'),
('Madrid', 'Madrid'),
('Manta', 'Manta'),
('Medina', 'Medina'),
('Mosquera', 'Mosquera'),
('Nariño', 'Nariño'),
('Nemocón', 'Nemocón'),
('Nilo', 'Nilo'),
('Nimaima', 'Nimaima'),
('Nocaima', 'Nocaima'),
('Venecia', 'Venecia'),
('Pacho', 'Pacho'),
('Paime', 'Paime'),
('Pandi', 'Pandi'),
('Paratebueno', 'Paratebueno'),
('Pasca', 'Pasca'),
('Puerto salgar', 'Puerto salgar'),
('Pulí', 'Pulí'),
('Quebradanegra', 'Quebradanegra'),
('Quetame', 'Quetame'),
('Quipile', 'Quipile'),
('Apulo', 'Apulo'),
('Ricaurte', 'Ricaurte'),
('San antonio del tequendama', 'San antonio del tequendama'),
('San bernardo', 'San bernardo'),
('San cayetano', 'San cayetano'),
('San francisco', 'San francisco'),
('San juan de rioseco', 'San juan de rioseco'),
('Sasaima', 'Sasaima'),
('Sesquilé', 'Sesquilé'),
('Sibaté', 'Sibaté'),
('Silvania', 'Silvania'),
('Simijaca', 'Simijaca'),
('Soacha', 'Soacha'),
('Sopó', 'Sopó'),
('Subachoque', 'Subachoque'),
('Suesca', 'Suesca'),
('Supatá', 'Supatá'),
('Susa', 'Susa'),
('Sutatausa', 'Sutatausa'),
('Tabio', 'Tabio'),
('Tausa', 'Tausa'),
('Tena', 'Tena'),
('Tenjo', 'Tenjo'),
('Tibacuy', 'Tibacuy'),
('Tibirita', 'Tibirita'),
('Tocaima', 'Tocaima'),
('Tocancipá', 'Tocancipá'),
('Topaipí', 'Topaipí'),
('Ubalá', 'Ubalá'),
('Ubaque', 'Ubaque'),
('Villa de san diego de ubaté', 'Villa de san diego de ubaté'),
('Une', 'Une'),
('Útica', 'Útica'),
('Vergara', 'Vergara'),
('Vianí', 'Vianí'),
('Villagómez', 'Villagómez'),
('Villapinzón', 'Villapinzón'),
('Villeta', 'Villeta'),
('Viotá', 'Viotá'),
('Yacopí', 'Yacopí'),
('Zipacón', 'Zipacón'),
('Zipaquirá', 'Zipaquirá'),
('Quibdó', 'Quibdó'),
('Acandí', 'Acandí'),
('Alto baudó', 'Alto baudó'),
('Atrato', 'Atrato'),
('Bagadó', 'Bagadó'),
('Bahía solano', 'Bahía solano'),
('Bajo baudó', 'Bajo baudó'),
('Bojayá', 'Bojayá'),
('El cantón del san pablo', 'El cantón del san pablo'),
('Carmen del darién', 'Carmen del darién'),
('Cértegui', 'Cértegui'),
('Condoto', 'Condoto'),
('El carmen de atrato', 'El carmen de atrato'),
('El litoral del san juan', 'El litoral del san juan'),
('Istmina', 'Istmina'),
('Juradó', 'Juradó'),
('Lloró', 'Lloró'),
('Medio atrato', 'Medio atrato'),
('Medio baudó', 'Medio baudó'),
('Medio san juan', 'Medio san juan'),
('Nóvita', 'Nóvita'),
('Nuquí', 'Nuquí'),
('Río iró', 'Río iró'),
('Río quito', 'Río quito'),
('Riosucio', 'Riosucio'),
('San josé del palmar', 'San josé del palmar'),
('Sipí', 'Sipí'),
('Tadó', 'Tadó'),
('Unguía', 'Unguía'),
('Unión panamericana', 'Unión panamericana'),
('Neiva', 'Neiva'),
('Acevedo', 'Acevedo'),
('Agrado', 'Agrado'),
('Aipe', 'Aipe'),
('Algeciras', 'Algeciras'),
('Altamira', 'Altamira'),
('Baraya', 'Baraya'),
('Campoalegre', 'Campoalegre'),
('Colombia', 'Colombia'),
('Elías', 'Elías'),
('Garzón', 'Garzón'),
('Gigante', 'Gigante'),
('Guadalupe', 'Guadalupe'),
('Hobo', 'Hobo'),
('Íquira', 'Íquira'),
('Isnos', 'Isnos'),
('La argentina', 'La argentina'),
('La plata', 'La plata'),
('Nátaga', 'Nátaga'),
('Oporapa', 'Oporapa'),
('Paicol', 'Paicol'),
('Palermo', 'Palermo'),
('Palestina', 'Palestina'),
('Pital', 'Pital'),
('Pitalito', 'Pitalito'),
('Rivera', 'Rivera'),
('Saladoblanco', 'Saladoblanco'),
('San agustín', 'San agustín'),
('Santa maría', 'Santa maría'),
('Suaza', 'Suaza'),
('Tarqui', 'Tarqui'),
('Tesalia', 'Tesalia'),
('Tello', 'Tello'),
('Teruel', 'Teruel'),
('Timaná', 'Timaná'),
('Villavieja', 'Villavieja'),
('Yaguará', 'Yaguará'),
('Riohacha', 'Riohacha'),
('Albania', 'Albania'),
('Barrancas', 'Barrancas'),
('Dibulla', 'Dibulla'),
('Distracción', 'Distracción'),
('El molino', 'El molino'),
('Fonseca', 'Fonseca'),
('Hatonuevo', 'Hatonuevo'),
('La jagua del pilar', 'La jagua del pilar'),
('Maicao', 'Maicao'),
('Manaure', 'Manaure'),
('San juan del cesar', 'San juan del cesar'),
('Uribia', 'Uribia'),
('Urumita', 'Urumita'),
('Villanueva', 'Villanueva'),
('Santa marta', 'Santa marta'),
('Algarrobo', 'Algarrobo'),
('Aracataca', 'Aracataca'),
('Ariguaní', 'Ariguaní'),
('Cerro de san antonio', 'Cerro de san antonio'),
('Chivolo', 'Chivolo'),
('Ciénaga', 'Ciénaga'),
('Concordia', 'Concordia'),
('El banco', 'El banco'),
('El piñón', 'El piñón'),
('El retén', 'El retén'),
('Fundación', 'Fundación'),
('Guamal', 'Guamal'),
('Nueva granada', 'Nueva granada'),
('Pedraza', 'Pedraza'),
('Pijiño del carmen', 'Pijiño del carmen'),
('Pivijay', 'Pivijay'),
('Plato', 'Plato'),
('Puebloviejo', 'Puebloviejo'),
('Remolino', 'Remolino'),
('Sabanas de san ángel', 'Sabanas de san ángel'),
('Salamina', 'Salamina'),
('San sebastián de buenavista', 'San sebastián de buenavista'),
('San zenón', 'San zenón'),
('Santa ana', 'Santa ana'),
('Santa bárbara de pinto', 'Santa bárbara de pinto'),
('Sitionuevo', 'Sitionuevo'),
('Tenerife', 'Tenerife'),
('Zapayán', 'Zapayán'),
('Zona bananera', 'Zona bananera'),
('Villavicencio', 'Villavicencio'),
('Acacías', 'Acacías'),
('Barranca de upía', 'Barranca de upía'),
('Cabuyaro', 'Cabuyaro'),
('Castilla la nueva', 'Castilla la nueva'),
('Cubarral', 'Cubarral'),
('Cumaral', 'Cumaral'),
('El calvario', 'El calvario'),
('El castillo', 'El castillo'),
('El dorado', 'El dorado'),
('Fuente de oro', 'Fuente de oro'),
('Granada', 'Granada'),
('Guamal', 'Guamal'),
('Mapiripán', 'Mapiripán'),
('Mesetas', 'Mesetas'),
('La macarena', 'La macarena'),
('Uribe', 'Uribe'),
('Lejanías', 'Lejanías'),
('Puerto concordia', 'Puerto concordia'),
('Puerto gaitán', 'Puerto gaitán'),
('Puerto lópez', 'Puerto lópez'),
('Puerto lleras', 'Puerto lleras'),
('Puerto rico', 'Puerto rico'),
('Restrepo', 'Restrepo'),
('San carlos de guaroa', 'San carlos de guaroa'),
('San juan de arama', 'San juan de arama'),
('San juanito', 'San juanito'),
('San martín', 'San martín'),
('Vistahermosa', 'Vistahermosa'),
('Pasto', 'Pasto'),
('Albán', 'Albán'),
('Aldana', 'Aldana'),
('Ancuyá', 'Ancuyá'),
('Arboleda', 'Arboleda'),
('Barbacoas', 'Barbacoas'),
('Belén', 'Belén'),
('Buesaco', 'Buesaco'),
('Colón', 'Colón'),
('Consacá', 'Consacá'),
('Contadero', 'Contadero'),
('Córdoba', 'Córdoba'),
('Cuaspúd', 'Cuaspúd'),
('Cumbal', 'Cumbal'),
('Cumbitara', 'Cumbitara'),
('Chachagüí', 'Chachagüí'),
('El charco', 'El charco'),
('El peñol', 'El peñol'),
('El rosario', 'El rosario'),
('El tablón de gómez', 'El tablón de gómez'),
('El tambo', 'El tambo'),
('Funes', 'Funes'),
('Guachucal', 'Guachucal'),
('Guaitarilla', 'Guaitarilla'),
('Gualmatán', 'Gualmatán'),
('Iles', 'Iles'),
('Imués', 'Imués'),
('Ipiales', 'Ipiales'),
('La cruz', 'La cruz'),
('La florida', 'La florida'),
('La llanada', 'La llanada'),
('La tola', 'La tola'),
('La unión', 'La unión'),
('Leiva', 'Leiva'),
('Linares', 'Linares'),
('Los andes', 'Los andes'),
('Magüí', 'Magüí'),
('Mallama', 'Mallama'),
('Mosquera', 'Mosquera'),
('Nariño', 'Nariño'),
('Olaya herrera', 'Olaya herrera'),
('Ospina', 'Ospina'),
('Francisco pizarro', 'Francisco pizarro'),
('Policarpa', 'Policarpa'),
('Potosí', 'Potosí'),
('Providencia', 'Providencia'),
('Puerres', 'Puerres'),
('Pupiales', 'Pupiales'),
('Ricaurte', 'Ricaurte'),
('Roberto payán', 'Roberto payán'),
('Samaniego', 'Samaniego'),
('Sandoná', 'Sandoná'),
('San bernardo', 'San bernardo'),
('San lorenzo', 'San lorenzo'),
('San pablo', 'San pablo'),
('San pedro de cartago', 'San pedro de cartago'),
('Santa bárbara', 'Santa bárbara'),
('Santacruz', 'Santacruz'),
('Sapuyes', 'Sapuyes'),
('Taminango', 'Taminango'),
('Tangua', 'Tangua'),
('San andrés de tumaco', 'San andrés de tumaco'),
('Túquerres', 'Túquerres'),
('Yacuanquer', 'Yacuanquer'),
('Cúcuta', 'Cúcuta'),
('Ábrego', 'Ábrego'),
('Arboledas', 'Arboledas'),
('Bochalema', 'Bochalema'),
('Bucarasica', 'Bucarasica'),
('Cácota', 'Cácota'),
('Cáchira', 'Cáchira'),
('Chinácota', 'Chinácota'),
('Chitagá', 'Chitagá'),
('Convención', 'Convención'),
('Cucutilla', 'Cucutilla'),
('Durania', 'Durania'),
('El carmen', 'El carmen'),
('El tarra', 'El tarra'),
('El zulia', 'El zulia'),
('Gramalote', 'Gramalote'),
('Hacarí', 'Hacarí'),
('Herrán', 'Herrán'),
('Labateca', 'Labateca'),
('La esperanza', 'La esperanza'),
('La playa', 'La playa'),
('Los patios', 'Los patios'),
('Lourdes', 'Lourdes'),
('Mutiscua', 'Mutiscua'),
('Ocaña', 'Ocaña'),
('Pamplona', 'Pamplona'),
('Pamplonita', 'Pamplonita'),
('Puerto santander', 'Puerto santander'),
('Ragonvalia', 'Ragonvalia'),
('Salazar', 'Salazar'),
('San calixto', 'San calixto'),
('San cayetano', 'San cayetano'),
('Santiago', 'Santiago'),
('Sardinata', 'Sardinata'),
('Silos', 'Silos'),
('Teorama', 'Teorama'),
('Tibú', 'Tibú'),
('Toledo', 'Toledo'),
('Villa caro', 'Villa caro'),
('Villa del rosario', 'Villa del rosario'),
('Armenia', 'Armenia'),
('Buenavista', 'Buenavista'),
('Calarcá', 'Calarcá'),
('Circasia', 'Circasia'),
('Córdoba', 'Córdoba'),
('Filandia', 'Filandia'),
('Génova', 'Génova'),
('La tebaida', 'La tebaida'),
('Montenegro', 'Montenegro'),
('Pijao', 'Pijao'),
('Quimbaya', 'Quimbaya'),
('Salento', 'Salento'),
('Pereira', 'Pereira'),
('Apía', 'Apía'),
('Balboa', 'Balboa'),
('Belén de umbría', 'Belén de umbría'),
('Dosquebradas', 'Dosquebradas'),
('Guática', 'Guática'),
('La celia', 'La celia'),
('La virginia', 'La virginia'),
('Marsella', 'Marsella'),
('Mistrató', 'Mistrató'),
('Pueblo rico', 'Pueblo rico'),
('Quinchía', 'Quinchía'),
('Santa rosa de cabal', 'Santa rosa de cabal'),
('Santuario', 'Santuario'),
('Bucaramanga', 'Bucaramanga'),
('Aguada', 'Aguada'),
('Albania', 'Albania'),
('Aratoca', 'Aratoca'),
('Barbosa', 'Barbosa'),
('Barichara', 'Barichara'),
('Barrancabermeja', 'Barrancabermeja'),
('Betulia', 'Betulia'),
('Bolívar', 'Bolívar'),
('Cabrera', 'Cabrera'),
('California', 'California'),
('Capitanejo', 'Capitanejo'),
('Carcasí', 'Carcasí'),
('Cepitá', 'Cepitá'),
('Cerrito', 'Cerrito'),
('Charalá', 'Charalá'),
('Charta', 'Charta'),
('Chima', 'Chima'),
('Chipatá', 'Chipatá'),
('Cimitarra', 'Cimitarra'),
('Concepción', 'Concepción'),
('Confines', 'Confines'),
('Contratación', 'Contratación'),
('Coromoro', 'Coromoro'),
('Curití', 'Curití'),
('El carmen de chucurí', 'El carmen de chucurí'),
('El guacamayo', 'El guacamayo'),
('El peñón', 'El peñón'),
('El playón', 'El playón'),
('Encino', 'Encino'),
('Enciso', 'Enciso'),
('Florián', 'Florián'),
('Floridablanca', 'Floridablanca'),
('Galán', 'Galán'),
('Gámbita', 'Gámbita'),
('Girón', 'Girón'),
('Guaca', 'Guaca'),
('Guadalupe', 'Guadalupe'),
('Guapotá', 'Guapotá'),
('Guavatá', 'Guavatá'),
('Güepsa', 'Güepsa'),
('Hato', 'Hato'),
('Jesús maría', 'Jesús maría'),
('Jordán', 'Jordán'),
('La belleza', 'La belleza'),
('Landázuri', 'Landázuri'),
('La paz', 'La paz'),
('Lebrija', 'Lebrija'),
('Los santos', 'Los santos'),
('Macaravita', 'Macaravita'),
('Málaga', 'Málaga'),
('Matanza', 'Matanza'),
('Mogotes', 'Mogotes'),
('Molagavita', 'Molagavita'),
('Ocamonte', 'Ocamonte'),
('Oiba', 'Oiba'),
('Onzaga', 'Onzaga'),
('Palmar', 'Palmar'),
('Palmas del socorro', 'Palmas del socorro'),
('Páramo', 'Páramo'),
('Piedecuesta', 'Piedecuesta'),
('Pinchote', 'Pinchote'),
('Puente nacional', 'Puente nacional'),
('Puerto parra', 'Puerto parra'),
('Puerto wilches', 'Puerto wilches'),
('Rionegro', 'Rionegro'),
('Sabana de torres', 'Sabana de torres'),
('San andrés', 'San andrés'),
('San benito', 'San benito'),
('San gil', 'San gil'),
('San joaquín', 'San joaquín'),
('San josé de miranda', 'San josé de miranda'),
('San miguel', 'San miguel'),
('San vicente de chucurí', 'San vicente de chucurí'),
('Santa bárbara', 'Santa bárbara'),
('Santa helena del opón', 'Santa helena del opón'),
('Simacota', 'Simacota'),
('Socorro', 'Socorro'),
('Suaita', 'Suaita'),
('Sucre', 'Sucre'),
('Suratá', 'Suratá'),
('Tona', 'Tona'),
('Valle de san josé', 'Valle de san josé'),
('Vélez', 'Vélez'),
('Vetas', 'Vetas'),
('Villanueva', 'Villanueva'),
('Zapatoca', 'Zapatoca'),
('Sincelejo', 'Sincelejo'),
('Buenavista', 'Buenavista'),
('Caimito', 'Caimito'),
('Colosó', 'Colosó'),
('Corozal', 'Corozal'),
('Coveñas', 'Coveñas'),
('Chalán', 'Chalán'),
('El roble', 'El roble'),
('Galeras', 'Galeras'),
('Guaranda', 'Guaranda'),
('La unión', 'La unión'),
('Los palmitos', 'Los palmitos'),
('Majagual', 'Majagual'),
('Morroa', 'Morroa'),
('Ovejas', 'Ovejas'),
('Palmito', 'Palmito'),
('Sampués', 'Sampués'),
('San benito abad', 'San benito abad'),
('San juan de betulia', 'San juan de betulia'),
('San marcos', 'San marcos'),
('San onofre', 'San onofre'),
('San pedro', 'San pedro'),
('San luis de sincé', 'San luis de sincé'),
('Sucre', 'Sucre'),
('Santiago de tolú', 'Santiago de tolú'),
('Tolú viejo', 'Tolú viejo'),
('Ibagué', 'Ibagué'),
('Alpujarra', 'Alpujarra'),
('Alvarado', 'Alvarado'),
('Ambalema', 'Ambalema'),
('Anzoátegui', 'Anzoátegui'),
('Armero guayabal', 'Armero guayabal'),
('Ataco', 'Ataco'),
('Cajamarca', 'Cajamarca'),
('Carmen de apicalá', 'Carmen de apicalá'),
('Casabianca', 'Casabianca'),
('Chaparral', 'Chaparral'),
('Coello', 'Coello'),
('Coyaima', 'Coyaima'),
('Cunday', 'Cunday'),
('Dolores', 'Dolores'),
('Espinal', 'Espinal'),
('Falan', 'Falan'),
('Flandes', 'Flandes'),
('Fresno', 'Fresno'),
('Guamo', 'Guamo'),
('Herveo', 'Herveo'),
('Honda', 'Honda'),
('Icononzo', 'Icononzo'),
('Lérida', 'Lérida'),
('Líbano', 'Líbano'),
('San sebastián de mariquita', 'San sebastián de mariquita'),
('Melgar', 'Melgar'),
('Murillo', 'Murillo'),
('Natagaima', 'Natagaima'),
('Ortega', 'Ortega'),
('Palocabildo', 'Palocabildo'),
('Piedras', 'Piedras'),
('Planadas', 'Planadas'),
('Prado', 'Prado'),
('Purificación', 'Purificación'),
('Rioblanco', 'Rioblanco'),
('Roncesvalles', 'Roncesvalles'),
('Rovira', 'Rovira'),
('Saldaña', 'Saldaña'),
('San antonio', 'San antonio'),
('San luis', 'San luis'),
('Santa isabel', 'Santa isabel'),
('Suárez', 'Suárez'),
('Valle de san juan', 'Valle de san juan'),
('Venadillo', 'Venadillo'),
('Villahermosa', 'Villahermosa'),
('Villarrica', 'Villarrica'),
('Cali', 'Cali'),
('Alcalá', 'Alcalá'),
('Andalucía', 'Andalucía'),
('Ansermanuevo', 'Ansermanuevo'),
('Argelia', 'Argelia'),
('Bolívar', 'Bolívar'),
('Buenaventura', 'Buenaventura'),
('Guadalajara de buga', 'Guadalajara de buga'),
('Bugalagrande', 'Bugalagrande'),
('Caicedonia', 'Caicedonia'),
('Calima', 'Calima'),
('Candelaria', 'Candelaria'),
('Cartago', 'Cartago'),
('Dagua', 'Dagua'),
('El águila', 'El águila'),
('El cairo', 'El cairo'),
('El cerrito', 'El cerrito'),
('El dovio', 'El dovio'),
('Florida', 'Florida'),
('Ginebra', 'Ginebra'),
('Guacarí', 'Guacarí'),
('Jamundí', 'Jamundí'),
('La cumbre', 'La cumbre'),
('La unión', 'La unión'),
('La victoria', 'La victoria'),
('Obando', 'Obando'),
('Palmira', 'Palmira'),
('Pradera', 'Pradera'),
('Restrepo', 'Restrepo'),
('Riofrío', 'Riofrío'),
('Roldanillo', 'Roldanillo'),
('San pedro', 'San pedro'),
('Sevilla', 'Sevilla'),
('Toro', 'Toro'),
('Trujillo', 'Trujillo'),
('Tuluá', 'Tuluá'),
('Ulloa', 'Ulloa'),
('Versalles', 'Versalles'),
('Vijes', 'Vijes'),
('Yotoco', 'Yotoco'),
('Yumbo', 'Yumbo'),
('Zarzal', 'Zarzal'),
('Arauca', 'Arauca'),
('Arauquita', 'Arauquita'),
('Cravo norte', 'Cravo norte'),
('Fortul', 'Fortul'),
('Puerto rondón', 'Puerto rondón'),
('Saravena', 'Saravena'),
('Tame', 'Tame'),
('Yopal', 'Yopal'),
('Aguazul', 'Aguazul'),
('Chámeza', 'Chámeza'),
('Hato corozal', 'Hato corozal'),
('La salina', 'La salina'),
('Maní', 'Maní'),
('Monterrey', 'Monterrey'),
('Nunchía', 'Nunchía'),
('Orocué', 'Orocué'),
('Paz de ariporo', 'Paz de ariporo'),
('Pore', 'Pore'),
('Recetor', 'Recetor'),
('Sabanalarga', 'Sabanalarga'),
('Sácama', 'Sácama'),
('San luis de palenque', 'San luis de palenque'),
('Támara', 'Támara'),
('Tauramena', 'Tauramena'),
('Trinidad', 'Trinidad'),
('Villanueva', 'Villanueva'),
('Mocoa', 'Mocoa'),
('Colón', 'Colón'),
('Orito', 'Orito'),
('Puerto asís', 'Puerto asís'),
('Puerto caicedo', 'Puerto caicedo'),
('Puerto guzmán', 'Puerto guzmán'),
('Puerto leguízamo', 'Puerto leguízamo'),
('Sibundoy', 'Sibundoy'),
('San francisco', 'San francisco'),
('San miguel', 'San miguel'),
('Santiago', 'Santiago'),
('Valle del guamuez', 'Valle del guamuez'),
('Villagarzón', 'Villagarzón'),
('San andrés', 'San andrés'),
('Providencia', 'Providencia'),
('Leticia', 'Leticia'),
('Puerto nariño', 'Puerto nariño'),
('Inírida', 'Inírida'),
('San josé del guaviare', 'San josé del guaviare'),
('Calamar', 'Calamar'),
('El retorno', 'El retorno'),
('Miraflores', 'Miraflores'),
('Mitú', 'Mitú'),
('Carurú', 'Carurú'),
('Taraira', 'Taraira'),
('Puerto carreño', 'Puerto carreño'),
('La primavera', 'La primavera'),
('Santa rosalía', 'Santa rosalía'),
('Cumaribo', 'Cumaribo') ]